Repository blackducksoftware/synopsys-operator, pull requests merged in 2019-11, with the labels that each got.

#1053 SMTP configuration
  pkg/polaris/ctl_polaris.go
  pkg/polaris/patcher.go
  pkg/polaris/types.go
  pkg/util/baseyamlutil.go
Labels: approved, lgtm, size/M

#1051 Update Dockerfiles
  Dockerfile
  Dockerfile-Operator.Dockerfile
Labels: approved, size/M

#1055 [master] Update Dockerfiles
  Dockerfile
  Dockerfile-Operator.Dockerfile
Labels: approved, lgtm, size/M

#1054 [master] SMTP configuration
  pkg/polaris/ctl_polaris.go
  pkg/polaris/patcher.go
  pkg/polaris/types.go
  pkg/util/baseyamlutil.go
Labels: approved, lgtm, size/M

#1056 Polaris platform license
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/patcher.go
  pkg/polaris/types.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/L

#1061 a non-breaking, less bike-sheddy version of #1059
  .travis.yml
  hack/create_k8s_cluster_and_run_synopsysctl.sh
  hack/polaris_platform_license_path.json
  hack/test_synopsysctl_native.sh
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/types.go
Labels: approved, size/L

#1062 [master] a non-breaking, less bike-sheddy version of #1059
  .travis.yml
  hack/create_k8s_cluster_and_run_synopsysctl.sh
  hack/polaris_platform_license_path.json
  hack/test_synopsysctl_native.sh
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/types.go
Labels: approved, lgtm, size/L

#1060 Fix overwriting pvc issue in mock mode by removing '-' prefix
  pkg/synopsysctl/cmd_create.go
Labels: approved, size/XS

#1059 organize polaris cli parameters
  hack/create_k8s_cluster_and_run_synopsysctl.sh
  hack/test_synopsysctl_native.sh
  pkg/polaris/ctl_polaris.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#1069 Various fixes
  hack/create_k8s_cluster_and_run_synopsysctl.sh
  hack/test_synopsysctl_native.sh
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/patcher.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#1070 [master] organize polaris cli parameters
  hack/create_k8s_cluster_and_run_synopsysctl.sh
  hack/test_synopsysctl_native.sh
  pkg/polaris/ctl_polaris.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#1071 [master] Various fixes
  hack/create_k8s_cluster_and_run_synopsysctl.sh
  hack/test_synopsysctl_native.sh
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/patcher.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#1083 Verify that the version exist before deployment
  pkg/polaris/creater.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/polaris.go
Labels: approved, lgtm, size/M

#1085 [master] Verify that the version exist before deployment
  pkg/polaris/creater.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/polaris.go
Labels: approved, lgtm, size/M

#1081 Fix BlackDuck PVC Issues: Solr and "-"
  examples/synopsysctl/pvc.json
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/util/pvc.go
  pkg/apps/blackduck/v1/containers/imageTags.go
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v2/containers/pvc.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_create_test.go
Labels: approved, size/L

#1086 Initial Files for BDBA Support
  pkg/bdba/constants.go
  pkg/bdba/creater.go
  pkg/bdba/ctl_bdba.go
  pkg/bdba/patcher.go
  pkg/bdba/types.go
  pkg/synopsysctl/bdba.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/baseyamlutil.go
Labels: approved, size/XL

#1088 Hide flags that cannot be updated
  pkg/polaris/ctl_polaris.go
  pkg/synopsysctl/cmd_delete.go
Labels: approved, lgtm, size/M

#1082 fix permission issue and remove prometheus metrics
  cmd/operator/run.go
  pkg/protoform/controller.go
  pkg/soperator/prometheus.go
  pkg/soperator/prometheus_resources.go
  pkg/soperator/soperator_creater.go
  pkg/soperator/soperator_resources.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XL

#1090 [master] fix permission issue and remove prometheus metrics
  cmd/operator/run.go
  pkg/protoform/controller.go
  pkg/soperator/prometheus.go
  pkg/soperator/prometheus_resources.go
  pkg/soperator/soperator_creater.go
  pkg/soperator/soperator_resources.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XL

#1089 [master] Hide flags that cannot be updated
  pkg/polaris/ctl_polaris.go
  pkg/synopsysctl/cmd_delete.go
Labels: approved, lgtm, size/M

#1093 Remove --create-organization flag
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_serve_UI.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/polaris.go
Labels: approved, lgtm, size/S

#1094 [master] Remove --create-organization flag
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_serve_UI.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/polaris.go
Labels: approved, lgtm, size/S

#1095 add support for Black Duck 2019.10.1 and Alert 5.0.1
  cmd/operator-ui/actions/blackducks.go
  pkg/apps/alert/latest/alert_versions.go
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#1099 BlackDuck Solr and "-" pvc Fix
  examples/synopsysctl/pvc.json
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/util/pvc.go
  pkg/apps/blackduck/v2/containers/pvc.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_create_test.go
Labels: approved, size/L

#1098 Added solr back to black duck v1
  pkg/apps/blackduck/v1/containers/imageTags.go
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/synopsysctl/cmd_create_test.go
Labels: approved, lgtm, size/M

#1104 disable the UI for the 2019.11.0 synopsysctl release
  pkg/synopsysctl/cmd_serve_UI.go
Labels: approved, lgtm, size/S

#1092 Artifactory and Quay Processors added to OpsSight
  pkg/api/opssight/v1/types.go
  pkg/opssight/configmap.go
  pkg/opssight/creater_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/opssight/perceivers.go
  pkg/opssight/prometheus.go
  pkg/opssight/specconfig.go
  pkg/util/common.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/L

#1107 add link to docs in create polaris help; edit help texts
  pkg/polaris/ctl_polaris.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, size/M

#1108 [master] add link to docs in create polaris help; edit help texts
  pkg/polaris/ctl_polaris.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#1109 add link to create native and update
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, size/XS

#1110 [master] add link to create native and update
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#1106 [master] Artifactory and Quay Processors added to OpsSight
  pkg/api/opssight/v1/types.go
  pkg/opssight/configmap.go
  pkg/opssight/creater_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/opssight/perceivers.go
  pkg/opssight/prometheus.go
  pkg/opssight/specconfig.go
  pkg/util/common.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/L

#1111 update go mods for master
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  go.mod
  go.sum
Labels: approved, size/L

#1112 update polaris yaml version to test 2019.11
  .travis.yml
Labels: approved, size/XS

#1113 fix is greater than or equal to version method
  pkg/util/helpers.go
  pkg/util/helpers_test.go
Labels: approved, lgtm, size/L

#1114 [master] fix is greater than or equal to version method
  pkg/util/helpers.go
  pkg/util/helpers_test.go
Labels: approved, lgtm, size/L

#1115 synopsysctl exits if it cannot set a flag properly
  pkg/alert/ctl_alert.go
  pkg/blackduck/ctl_blackduck.go
  pkg/opssight/ctl_opssight.go
Labels: approved, lgtm, size/M

#1117 [release-2019.11.x] update polaris yaml version to test 2019.11
  .travis.yml
Labels: approved, lgtm, size/XS

#1116 [master] synopsysctl exits if it cannot set a flag properly
  pkg/alert/ctl_alert.go
  pkg/blackduck/ctl_blackduck.go
  pkg/opssight/ctl_opssight.go
Labels: approved, lgtm, size/M

#1121 pod processor bug fix
  pkg/soperator/soperator_resources.go
Labels: approved, lgtm, size/XS

#1122 [master] pod processor bug fix
  pkg/soperator/soperator_resources.go
Labels: approved, lgtm, size/XS

#1100 fix memory limits to be expressed as power of two instead of SI unit
  pkg/apps/blackduck/latest/containers/constants.go
  pkg/apps/blackduck/latest/containers/containerflavor.go
  pkg/apps/blackduck/v1/containers/constants.go
  pkg/apps/blackduck/v1/containers/containerflavor.go
  pkg/apps/blackduck/v2/containers/constants.go
  pkg/apps/blackduck/v2/containers/containerflavor.go
Labels: approved, do-not-merge/hold, size/XL
