Repository blackducksoftware/synopsys-operator, pull requests merged in 2019-07, with the labels that each got.

#609 Remove init container for postgres + remove rabbitmq data volume
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/init.go
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/init.go
  pkg/apps/database/postgres/postgres.go
Labels: approved, lgtm, size/M

#610 [release-2019.6.x] Remove init container for postgres + remove rabbitmq data volume
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/init.go
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/init.go
  pkg/apps/database/postgres/postgres.go
Labels: approved, lgtm, size/M

#611 remove pvc and added scale down Synopsys Operator
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/M

#612 [release-2019.6.x] remove pvc and added scale down Synopsys Operator
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/M

#615 opssight migrate issue
  pkg/synopsysctl/cmd_migrate.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#616 [release-2019.6.x] opssight migrate issue
  pkg/synopsysctl/cmd_migrate.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#621 synopsysctl update has access to resource clients
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_root.go
Labels: approved, lgtm, size/XS

#622 Synopsys Operator defaults to Kubernetes for mock mode
  pkg/soperator/utils.go
Labels: approved, lgtm, size/S

#623 [release-2019.6.x] synopsysctl update has access to resource clients
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_root.go
Labels: approved, lgtm, size/XS

#624 [release-2019.6.x] Synopsys Operator defaults to Kubernetes for mock mode
  pkg/soperator/utils.go
Labels: approved, lgtm, size/S

#640 [release 2019.6.x] stop/start use name (not namespace) to get resource
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
Labels: approved, lgtm, size/XS

#629 multiple volume fix
  go.mod
  go.sum
  pkg/apps/blackduck/latest/containers/constants.go
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/constants.go
  pkg/apps/blackduck/v1/containers/postgres.go
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/L

#635 error due to deploying multiple bd into one namespace is more clear
  cmd/operator-ui/actions/blackducks.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/XS

#643 [release-2019.6.x] error due to deploying multiple bd into one namespace is more clear
  cmd/operator-ui/actions/blackducks.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/XS

#644 multiple volume fix
  go.mod
  go.sum
  pkg/apps/blackduck/latest/containers/constants.go
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/constants.go
  pkg/apps/blackduck/v1/containers/postgres.go
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/L

#638 stop deploy and db-migrate can take in multiple resource names (#451)
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
Labels: approved, lgtm, size/L

#646 migrate cleanup command
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/M

#648 [release-2019.6.x] migrate cleanup command
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/M

#636 remove examples of opssight in namespaced mode
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/S

#649 synopsysctl can get resources in all namespaces
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/M

#650 [release-2019.6.x] synopsysctl can get resources in all namespaces
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/M

#657 Fix proxy certificate issue
  pkg/util/readFileData.go
Labels: approved, lgtm, size/XS

#654 synopsysctl attempts to destroy all operators
  pkg/synopsysctl/cmd_destroy.go
Labels: approved, lgtm, size/XS

#658 [release-2019.6.x] Fix proxy certificate issue
  pkg/util/readFileData.go
Labels: approved, lgtm, size/XS

#659 [release-2019.6.x] synopsysctl attempts to destroy all operators
  pkg/synopsysctl/cmd_destroy.go
Labels: approved, lgtm, size/XS

#661 mock mode uses creater to get correct PVCs (#651)
  pkg/synopsysctl/cmd_create.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/L

#664 [release-2019.6.x] mock mode uses creater to get correct PVCs (#651)
  pkg/synopsysctl/cmd_create.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/L

#668 Fix blackduck registration
  pkg/apps/blackduck/latest/creater.go
Labels: approved, lgtm, size/XS

#669 Support latest OpsSight and Black Duck release
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/opssight/creater.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/M

#670 [release-2019.6.x] Support latest OpsSight and Black Duck release
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/opssight/creater.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/M

#666 add NodeAffinities to view of crd
  examples/deprecated/devNodeAffinityExample.json
  go.mod
  go.sum
  pkg/api/alert/v1/zz_generated.deepcopy.go
  pkg/api/blackduck/v1/types.go
  pkg/api/blackduck/v1/zz_generated.deepcopy.go
  pkg/api/opssight/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#671 [release-2019.6.x] add NodeAffinities to view of crd
  examples/deprecated/devNodeAffinityExample.json
  go.mod
  go.sum
  pkg/api/alert/v1/zz_generated.deepcopy.go
  pkg/api/blackduck/v1/types.go
  pkg/api/blackduck/v1/zz_generated.deepcopy.go
  pkg/api/opssight/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#672 synopsysctl does better checking for a valid image
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/S

#674 [release-2019.6.x] synopsysctl does better checking for a valid image
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/S

#676 fix for authentication host name and update master key
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/configmap.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/configmap.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#677 [release-2019.6.x] fix for authentication host name and update master key
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/configmap.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/configmap.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#675 migrate-command updates operator's image after migrating CRDs
  pkg/synopsysctl/cmd_migrate.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#660 Support openshift 4.1
  cmd/operator/run.go
  pkg/alert/crdinstaller.go
  pkg/apps/blackduck/blackduck.go
  pkg/blackduck/crdinstaller.go
  pkg/crdupdater/route.go
  pkg/opssight/crdinstaller.go
  pkg/soperator/soperator_creater.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#678 [release-2019.6.x] migrate-command updates operator's image after migrating CRDs
  pkg/synopsysctl/cmd_migrate.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#679 [release-2019.6.x] Support openshift 4.1
  cmd/operator/run.go
  pkg/alert/crdinstaller.go
  pkg/apps/blackduck/blackduck.go
  pkg/blackduck/crdinstaller.go
  pkg/crdupdater/route.go
  pkg/opssight/crdinstaller.go
  pkg/soperator/soperator_creater.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#665 add node affinity to the UI
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/L

#681 [release-2019.6.x] add node affinity to the UI
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/XL

#685 bd operator doesn't wait if a pod is failed or a container is terminated
  pkg/util/common.go
Labels: approved, lgtm, size/M

#687 [release-2019.6.x] bd operator doesn't wait if a pod is failed or a container is terminated
  pkg/util/common.go
Labels: approved, lgtm, size/M

#689 Fix UI following #667
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  go.mod
  go.sum
  pkg/apps/blackduck/components/configmap/global/v1/configmap.go
Labels: approved, size/M

#691 Fix #690
  pkg/opssight/specconfig.go
Labels: approved, lgtm, size/XS

#692 [release-2019.6.x] Fix #690
  pkg/opssight/specconfig.go
Labels: approved, lgtm, size/XS

#694 alert fix
  go.mod
  go.sum
  pkg/alert/crdinstaller.go
  pkg/apps/alert/latest/alertsecret.go
  pkg/apps/alert/latest/configmap.go
  pkg/apps/alert/latest/route.go
Labels: approved, lgtm, size/XL

#698 alert-fix
  pkg/alert/crdinstaller.go
  pkg/apps/alert/latest/alertsecret.go
  pkg/apps/alert/latest/configmap.go
  pkg/apps/alert/latest/route.go
Labels: approved, lgtm, size/S

#700 Multiple fixes
  pkg/apps/blackduck/components/rc/authentication/v1/component.go
  pkg/apps/blackduck/components/rc/binaryscanner/v1/component.go
  pkg/apps/blackduck/components/rc/cfssl/v1/component.go
  pkg/apps/blackduck/components/rc/documentation/v1/component.go
  pkg/apps/blackduck/components/rc/jobrunner/v1/component.go
  pkg/apps/blackduck/components/rc/postgres/v1/component.go
  pkg/apps/blackduck/components/rc/rabbitmq/v1/component.go
  pkg/apps/blackduck/components/rc/registration/v1/component.go
  pkg/apps/blackduck/components/rc/scan/v1/component.go
  pkg/apps/blackduck/components/rc/solr/v1/component.go
  pkg/apps/blackduck/components/rc/uploadcache/v1/component.go
  pkg/apps/blackduck/components/rc/webapplogstash/v1/component.go
  pkg/apps/blackduck/components/rc/webserver/v1/component.go
  pkg/apps/blackduck/components/rc/zookeeper/v1/component.go
  pkg/apps/blackduck/components/service/authentication/v1/service.go
  pkg/apps/blackduck/components/utils/limits.go
  pkg/apps/blackduck/sizes/v1/size.go
  pkg/apps/blackduck/types/types.go
  pkg/apps/store/store.go
Labels: approved, lgtm, size/XL

#701 Fix synopsysctl create native
  cmd/synopsysctl/main.go
  pkg/api/types.go
  pkg/apps/blackduck/blackduck.go
  pkg/apps/store/store.go
Labels: approved, lgtm, size/L

#705 support SaaS environment
  pkg/apps/blackduck/latest/containers/constants.go
  pkg/apps/blackduck/v1/containers/constants.go
Labels: approved, lgtm, size/M

#706 rename resource ctl commands and increase their modularity
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/ctl_interface.go
Labels: approved, lgtm, size/XXL

#710 Make postgres PV configurable in the operator UI
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/S

#711 travis fix
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/L

#713 Fix printing of PVC information in CRD spec #702
  pkg/api/blackduck/v1/types.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#714 move genPVC out of api
  pkg/api/blackduck/v1/types.go
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/components/pvc/v1/pvc.go
  pkg/apps/blackduck/components/pvc/v2/pvc.go
Labels: approved, lgtm, size/L

#718 Added missing copyright headers
  pkg/apps/blackduck/components/components.go
  pkg/apps/blackduck/components/configmap/database/v1/configmap.go
  pkg/apps/blackduck/components/configmap/global/v1/configmap.go
  pkg/apps/blackduck/components/pvc/v1/pvc.go
  pkg/apps/blackduck/components/pvc/v2/pvc.go
  pkg/apps/blackduck/components/rc/authentication/v1/component.go
  pkg/apps/blackduck/components/rc/binaryscanner/v1/component.go
  pkg/apps/blackduck/components/rc/cfssl/v1/component.go
  pkg/apps/blackduck/components/rc/documentation/v1/component.go
  pkg/apps/blackduck/components/rc/jobrunner/v1/component.go
  pkg/apps/blackduck/components/rc/postgres/v1/component.go
  pkg/apps/blackduck/components/rc/rabbitmq/v1/component.go
  pkg/apps/blackduck/components/rc/registration/v1/component.go
  pkg/apps/blackduck/components/rc/scan/v1/component.go
  pkg/apps/blackduck/components/rc/solr/v1/component.go
  pkg/apps/blackduck/components/rc/uploadcache/v1/component.go
  pkg/apps/blackduck/components/rc/utils/utils.go
  pkg/apps/blackduck/components/rc/webapplogstash/v1/component.go
  pkg/apps/blackduck/components/rc/webserver/v1/component.go
  pkg/apps/blackduck/components/rc/zookeeper/v1/component.go
  pkg/apps/blackduck/components/secret/authcertificate/v1/secret.go
  pkg/apps/blackduck/components/secret/postgres/v1/secret.go
  pkg/apps/blackduck/components/secret/proxycertificate/v1/secret.go
  pkg/apps/blackduck/components/secret/uploadcache/v1/secret.go
  pkg/apps/blackduck/components/secret/webcertificate/v1/secret.go
  pkg/apps/blackduck/components/service/authentication/v1/service.go
  pkg/apps/blackduck/components/service/cfssl/v1/service.go
  pkg/apps/blackduck/components/service/documentation/v1/service.go
  pkg/apps/blackduck/components/service/expose/v1/service.go
  pkg/apps/blackduck/components/service/logstash/v1/service.go
  pkg/apps/blackduck/components/service/postgres/v1/service.go
  pkg/apps/blackduck/components/service/rabbitmq/v1/service.go
  pkg/apps/blackduck/components/service/registration/v1/service.go
  pkg/apps/blackduck/components/service/scan/v1/service.go
  pkg/apps/blackduck/components/service/solr/v1/service.go
  pkg/apps/blackduck/components/service/uploadcache/v1/service.go
  pkg/apps/blackduck/components/service/webapp/v1/service.go
  pkg/apps/blackduck/components/service/webserver/v1/service.go
  pkg/apps/blackduck/components/service/zookeeper/v1/service.go
  pkg/apps/store/store.go
  pkg/apps/types/constants.go
  pkg/apps/types/public.go
  pkg/apps/types/types.go
  pkg/apps/utils/common.go
  pkg/size/size.go
Labels: approved, lgtm, size/XL
