Repository blackducksoftware/synopsys-operator, pull requests merged in 2019-09, with the labels that each got.

#812 opssight plugins
  .gitignore
  meta-builder/config/samples/opssight_runtime_objects.yaml
  meta-builder/config/samples/synopsys_v1_opssight.yaml
  meta-builder/controllers/alert_controller.go
  meta-builder/controllers/authserver_controller.go
  meta-builder/controllers/blackduck_controller.go
  meta-builder/controllers/matchlabels.go
  meta-builder/controllers/opssight_blackduck_controller.go
  meta-builder/controllers/opssight_blackduck_plugin.go
  meta-builder/controllers/opssight_controller.go
  meta-builder/controllers/opssight_mutator.go
  meta-builder/controllers/polaris_controller.go
  meta-builder/controllers/polarisdb_controller.go
  meta-builder/controllers/reporting_controller.go
  meta-builder/controllers/util/create_instruction_manual.go
  meta-builder/controllers/util/readFileData.go
  meta-builder/controllers/util/utils.go
  meta-builder/controllers/util/yaml_to_runtime_object_converter.go
  meta-builder/flying-dutchman/flying-dutchman.go
  meta-builder/go.mod
  meta-builder/go.sum
  meta-builder/main.go
Labels: approved, size/XXL

#811 add scanner cluster role binding only in openshift and for image processor
  go.sum
  pkg/opssight/creater.go
  pkg/opssight/specconfig.go
Labels: approved, lgtm, size/S

#814 fix registry configuration validation
  meta-builder/api/v1/types.go
  meta-builder/config/crd/bases/synopsys.com_alerts.yaml
  meta-builder/config/crd/bases/synopsys.com_blackducks.yaml
  meta-builder/config/crd/bases/synopsys.com_opssights.yaml
Labels: approved, lgtm, size/S

#815 resolved rerunning make issue - concurrent map write
  meta-builder/controllers/util/yaml_to_runtime_object_converter.go
  meta-builder/flying-dutchman/flying-dutchman.go
Labels: approved, size/S

#816 migrate fix and setting version fix while creating the app
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/util/helpers.go
Labels: approved, lgtm, size/L

#822 fix namespace rbac
  pkg/soperator/soperator_resources.go
Labels: approved, lgtm, size/XS

#821 cleanup
  meta-builder/controllers/controllers_utils/utils.go
  meta-builder/flying-dutchman/flying-dutchman.go
  meta-builder/flying-dutchman/instruction_manual.go
Labels: approved, size/L

#823 fixed the get error message
  pkg/synopsysctl/cmd_get.go
Labels: approved, lgtm, size/XS

#826 fix travis
  .travis.yml
Labels: approved, lgtm, size/XS

#825 port over Aditya's changes on top of master
  api/v1/polarisdb_types.go
  api/v1/reporting_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/synopsys.com_polarisdbs.yaml
  config/crd/bases/synopsys.com_reportings.yaml
  controllers/polarisdb_controller.go
  controllers/polarisdb_mutator.go
  controllers/reporting_controller.go
  controllers/reporting_mutator.go
  delete-list.txt
  synopsysctl/cmd_serve_UI.go
  synopsysctl/ctl_polaris.go
Labels: approved, size/L

#827 Add Polaris additional permissions + Fix operator imagePullPolicy + F…
  .gitignore
  Dockerfile
  go.mod
  go.sum
  main.go
  soperator/soperator_resources.go
  synopsysctl/cmd_create.go
  utils/crd_defaults.go
Labels: approved, lgtm, size/L

#828 Fix polaris native
  controllers/polarisdb_controller.go
Labels: approved, lgtm, size/S

#829 handle missing port from UI for Polaris and add default polarisDB spec to UI backend
  synopsysctl/cmd_serve_UI.go
Labels: approved, lgtm, size/S

#830 Fix polaris
  soperator/soperator_resources.go
  synopsysctl/cmd_create.go
  utils/crd_defaults.go
Labels: approved, lgtm, size/S

#831 synopsysctl handles default values instead of the ui
  operator-ui-ember/app/components/polaris-form.js
  operator-ui-ember/app/templates/components/polaris-form.hbs
  synopsysctl/cmd_serve_UI.go
Labels: approved, lgtm, size/M

#834 Fixes for Makefile and build synopsysctl and container
  Makefile
Labels: approved, lgtm, size/M

#835 Moved to containerized builds in make
  Makefile
Labels: approved, lgtm, size/M

#842 fix migrate from version
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/XS

#850 added a fix to make target for installing crds
  .gitignore
  Makefile
Labels: approved, lgtm, size/XS

#849 move setControllerReference inside the common flying-dutchman scheduler
  config/samples/alert_runtime_objects.yaml
  config/samples/synopsys-operator-config.json
  config/samples/synopsys_v1_alert.yaml
  controllers/alert_controller.go
  controllers/authserver_controller.go
  controllers/blackduck_controller.go
  controllers/opssight_controller.go
  controllers/polaris_controller.go
  controllers/polarisdb_controller.go
  controllers/reporting_controller.go
  flying-dutchman/flying-dutchman.go
Labels: approved, lgtm, size/L

#856 Add support for Polaris to synopsysctl
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  flying-dutchman/flying-dutchman.go
  flying-dutchman/instruction_manual.go
  go-directed-acyclic-graph/.gitignore
  go-directed-acyclic-graph/directed_graph.go
  go-directed-acyclic-graph/directed_graph_test.go
  go-directed-acyclic-graph/edge.go
  go-directed-acyclic-graph/graph.go
  go-directed-acyclic-graph/graph_test.go
  go-directed-acyclic-graph/node.go
  go-directed-acyclic-graph/output.go
  go-directed-acyclic-graph/output_test.go
  go-directed-acyclic-graph/sort.go
  go-directed-acyclic-graph/sort_test.go
  go-scheduler/.gitignore
  go-scheduler/scheduler.go
  go-scheduler/scheduler_test.go
  go-scheduler/task.go
  go-scheduler/task_test.go
  go.mod
  go.sum
  pkg/polaris/common_mutator.go
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/polarisDBMutator.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/polaris_controller.go
  pkg/polaris/types.go
  pkg/polaris/utils.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/helpers.go
Labels: approved, lgtm, size/XXL

#859 if no secrets, leave map uninitialized for the crudupdater
  cmd/operator-ui/go.sum
  go.mod
  pkg/apps/alert/latest/alertsecret.go
Labels: approved, lgtm, size/XS

#861 Improve HTTP error message
  pkg/polaris/creater.go
  pkg/polaris/polarisDBMutator.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/polaris_controller.go
  pkg/polaris/utils.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#858 Build will run locally by default, in containers for binary target. If
  .travis.yml
  Makefile
  go.mod
  hack/verify-govet.sh
Labels: approved, lgtm, size/L

#862 Fixed detection/usage of GOPATH in Makefile
  Makefile
Labels: approved, lgtm, size/XS

#863 fix get and update master key issue
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/S

#864 [release-2019.10.x] fix get and update master key issue
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/S

#865 Mount only src dir in container builds
  Makefile
Labels: approved, lgtm, size/S

#870 Pv size config
  pkg/polaris/common_mutator.go
  pkg/polaris/constants.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/polarisDBMutator.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/types.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/L

#869 convert rc to deployment for Alert and Black Duck resources
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/apps/alert/latest/cfsslreplicationcontroller.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v2/containers/authentication.go
  pkg/apps/blackduck/v2/containers/binaryscanner.go
  pkg/apps/blackduck/v2/containers/cfssl.go
  pkg/apps/blackduck/v2/containers/documentation.go
  pkg/apps/blackduck/v2/containers/jobrunner.go
  pkg/apps/blackduck/v2/containers/rabbitmq.go
  pkg/apps/blackduck/v2/containers/registration.go
  pkg/apps/blackduck/v2/containers/scan.go
  pkg/apps/blackduck/v2/containers/solr.go
  pkg/apps/blackduck/v2/containers/uploadcache.go
  pkg/apps/blackduck/v2/containers/webapplogstash.go
  pkg/apps/blackduck/v2/containers/webserver.go
  pkg/apps/blackduck/v2/containers/zookeeper.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/apps/database/postgres/postgres.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#871 [release-2019.10.x] convert rc to deployment for Alert and Black Duck resources
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/apps/alert/latest/cfsslreplicationcontroller.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v2/containers/authentication.go
  pkg/apps/blackduck/v2/containers/binaryscanner.go
  pkg/apps/blackduck/v2/containers/cfssl.go
  pkg/apps/blackduck/v2/containers/documentation.go
  pkg/apps/blackduck/v2/containers/jobrunner.go
  pkg/apps/blackduck/v2/containers/rabbitmq.go
  pkg/apps/blackduck/v2/containers/registration.go
  pkg/apps/blackduck/v2/containers/scan.go
  pkg/apps/blackduck/v2/containers/solr.go
  pkg/apps/blackduck/v2/containers/uploadcache.go
  pkg/apps/blackduck/v2/containers/webapplogstash.go
  pkg/apps/blackduck/v2/containers/webserver.go
  pkg/apps/blackduck/v2/containers/zookeeper.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/apps/database/postgres/postgres.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#867 Set the synopsysctl binary name based on arch instead of doing a move
  Makefile
Labels: approved, lgtm, size/XS

#872 [saas-2019.8.0] convert rc to deployment for Alert and Black Duck resources
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/apps/alert/latest/cfsslreplicationcontroller.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v2/containers/authentication.go
  pkg/apps/blackduck/v2/containers/binaryscanner.go
  pkg/apps/blackduck/v2/containers/cfssl.go
  pkg/apps/blackduck/v2/containers/documentation.go
  pkg/apps/blackduck/v2/containers/jobrunner.go
  pkg/apps/blackduck/v2/containers/rabbitmq.go
  pkg/apps/blackduck/v2/containers/registration.go
  pkg/apps/blackduck/v2/containers/scan.go
  pkg/apps/blackduck/v2/containers/solr.go
  pkg/apps/blackduck/v2/containers/uploadcache.go
  pkg/apps/blackduck/v2/containers/webapplogstash.go
  pkg/apps/blackduck/v2/containers/webserver.go
  pkg/apps/blackduck/v2/containers/zookeeper.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/apps/database/postgres/postgres.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#876 changed the deployment strategy
  pkg/util/common.go
Labels: approved, lgtm, size/XS

#877 [release-2019.10.x] changed the deployment strategy
  pkg/util/common.go
Labels: approved, lgtm, size/XS

#878 [saas-2019.8.0] changed the deployment strategy
  pkg/util/common.go
Labels: approved, lgtm, size/XS

#875 Set platforms for target based upon binaries that were built
  Makefile
Labels: approved, lgtm, size/XS

#881 Revert "changed the deployment strategy"
  pkg/util/common.go
Labels: approved, lgtm, size/XS

#880 Revert "convert rc to deployment for Alert and Black Duck resources"
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/apps/alert/latest/cfsslreplicationcontroller.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v2/containers/authentication.go
  pkg/apps/blackduck/v2/containers/binaryscanner.go
  pkg/apps/blackduck/v2/containers/cfssl.go
  pkg/apps/blackduck/v2/containers/documentation.go
  pkg/apps/blackduck/v2/containers/jobrunner.go
  pkg/apps/blackduck/v2/containers/rabbitmq.go
  pkg/apps/blackduck/v2/containers/registration.go
  pkg/apps/blackduck/v2/containers/scan.go
  pkg/apps/blackduck/v2/containers/solr.go
  pkg/apps/blackduck/v2/containers/uploadcache.go
  pkg/apps/blackduck/v2/containers/webapplogstash.go
  pkg/apps/blackduck/v2/containers/webserver.go
  pkg/apps/blackduck/v2/containers/zookeeper.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/apps/database/postgres/postgres.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#883 Revert "[saas-2019.8.0] changed the deployment strategy"
  pkg/util/common.go
Labels: approved, lgtm, size/XS

#882 Revert "[saas-2019.8.0] convert rc to deployment for Alert and Black Duck resources"
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/apps/alert/latest/cfsslreplicationcontroller.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v2/containers/authentication.go
  pkg/apps/blackduck/v2/containers/binaryscanner.go
  pkg/apps/blackduck/v2/containers/cfssl.go
  pkg/apps/blackduck/v2/containers/documentation.go
  pkg/apps/blackduck/v2/containers/jobrunner.go
  pkg/apps/blackduck/v2/containers/rabbitmq.go
  pkg/apps/blackduck/v2/containers/registration.go
  pkg/apps/blackduck/v2/containers/scan.go
  pkg/apps/blackduck/v2/containers/solr.go
  pkg/apps/blackduck/v2/containers/uploadcache.go
  pkg/apps/blackduck/v2/containers/webapplogstash.go
  pkg/apps/blackduck/v2/containers/webserver.go
  pkg/apps/blackduck/v2/containers/zookeeper.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/apps/database/postgres/postgres.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#886 Fix provision command
  pkg/synopsysctl/cmd_provision.go
Labels: approved, size/S

#888 added support for Black Duck 2019.8.1
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/S

#889 [release-2019.10.x] added support for Black Duck 2019.8.1
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/S

#854 Add handling routes to BlackDuck and Alert Controllers
  controllers/alert_controller.go
  controllers/alert_mutator.go
  controllers/blackduck_controller.go
  controllers/blackduck_mutator.go
Labels: approved, lgtm, size/L

#890 [release-2019.8.x] Use a storage class if set when claim size is set #866
  pkg/apps/blackduck/util/pvc.go
Labels: approved, lgtm, size/XS

#887 Alert 5.0.0 support
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/api/alert/v1/types.go
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alert_versions.go
  pkg/apps/alert/latest/alertcertificatesecret.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/soperator/soperator_resources.go
Labels: approved, lgtm, size/L

#891 Remove --environment-name flag
  pkg/polaris/ctl_polaris.go
  pkg/polaris/polarisDBMutator.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/polarisReportingMutator.go
  pkg/polaris/types.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_provision.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#892 [release-2019.10.x] Alert 5.0.0 support
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/api/alert/v1/types.go
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alert_versions.go
  pkg/apps/alert/latest/alertcertificatesecret.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/soperator/soperator_resources.go
Labels: approved, lgtm, size/L

#893 Set default reporting size
  pkg/polaris/ctl_polaris.go
  pkg/polaris/polarisReportingMutator.go
Labels: approved, lgtm, size/XS

#894 added support to send pvc sizes for db and minio services
  pkg/polaris/ctl_polaris.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/polarisProvisionMutator.go
  pkg/polaris/polarisReportingMutator.go
  pkg/polaris/types.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_provision.go
Labels: approved, lgtm, size/L

#895 alert 5.0.0 upgrade environs support, operator ui 2019.8.1 Black Duck support, scale down wait for pods to be deleted
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  go.mod
  go.sum
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
  pkg/util/helpers.go
  pkg/util/helpers_test.go
Labels: approved, lgtm, size/XXL

#897 Fixed issue with database restarting in migration mode #873
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v2/creater.go
  pkg/blackduck/crdhandler.go
Labels: approved, lgtm, size/XS

#898 [release-2019.10.x] Fixed issue with database restarting in migration mode #873
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v2/creater.go
  pkg/blackduck/crdhandler.go
Labels: approved, lgtm, size/XS

#899 alert 5.0.0 upgrade environs support, operator ui 2019.8.1 Black Duck support, scale down wait for pods to be deleted
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
  pkg/util/helpers.go
  pkg/util/helpers_test.go
Labels: approved, lgtm, size/L

#832 add a simple sanity cluster test using kind in travis
  .gitignore
  .travis.yml
  Makefile
  cover.out
Labels: approved, size/XL

#901 support saas sizes (#799)
  pkg/apps/blackduck/latest/containers/constants.go
  pkg/apps/blackduck/v1/containers/constants.go
  pkg/apps/blackduck/v2/containers/constants.go
Labels: approved

#902 fix to create directory for storing the master key
  pkg/synopsysctl/cmd_get.go
Labels: approved, lgtm, size/XS

#903 [release-2019.10.x] fix to create directory for storing the master key
  pkg/synopsysctl/cmd_get.go
Labels: approved, lgtm, size/XS

#904 [saas-2019.8.4] fix to create directory for storing the master key
  pkg/synopsysctl/cmd_get.go
Labels: approved, lgtm, size/XS

#906 Move provision to create
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/polarisProvisionMutator.go
  pkg/polaris/types.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_provision.go
Labels: approved, lgtm, size/L

#907 Add patch provision job
  pkg/polaris/common_mutator.go
  pkg/polaris/constants.go
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/polarisDBMutator.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/polarisProvisionMutator.go
  pkg/polaris/polarisReportingMutator.go
  pkg/polaris/types.go
  pkg/polaris/utils.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/helpers.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/L

#908 file path to directory path
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#909 [release-2019.10.x] file path to directory path
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#910 [saas-2019.8.4] file path to directory path
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#911 Merge create and update into a single function + delete old jobs duri…
  pkg/polaris/polarisDBMutator.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/polarisProvisionMutator.go
  pkg/polaris/polarisReportingMutator.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/polaris.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/XL

#912 new seal key validation
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#913 [release-2019.10.x] new seal key validation
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#914 [saas-2019.8.4] new seal key validation
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#915 get the namespace before applying the patch
  pkg/crdupdater/namespace.go
Labels: approved, lgtm, size/S

#917 [release-2019.10.x] get the namespace before applying the patch
  pkg/crdupdater/namespace.go
Labels: approved, lgtm, size/S

#918 [saas-2019.8.4] get the namespace before applying the patch
  pkg/crdupdater/namespace.go
Labels: approved, lgtm, size/S

#920 scale up rc is commented for patch rc
  pkg/blackduck/crdhandler.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#922 [saas-2019.8.4] scale up rc is commented for patch rc
  pkg/blackduck/crdhandler.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#921 [release-2019.10.x] scale up rc is commented for patch rc
  pkg/blackduck/crdhandler.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#924 fix scale up issue for upgrades
  pkg/crdupdater/replicationcontroller.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#925 [release-2019.10.x] fix scale up issue for upgrades
  pkg/crdupdater/replicationcontroller.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#926 [saas-2019.8.4] fix scale up issue for upgrades
  pkg/crdupdater/replicationcontroller.go
  pkg/util/common.go
Labels: approved, lgtm, size/M
