Repository blackducksoftware/synopsys-operator, pull requests merged in 2019-06, with the labels that each got.

#329 require postgres passwords
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/api/blackduck/v1/types.go
  pkg/api/opssight/v1/types.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/blackduck/util/helpers.go
  pkg/opssight/creater.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/opssight/plugins.go
  pkg/opssight/specconfig.go
  pkg/soperator/soperator.go
  pkg/soperator/soperator_resources.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/ctl_interface.go
  pkg/util/common.go
  pkg/webhook/blackduck.go
Labels: approved, lgtm, size/XL

#389 require postgres password in UI
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/S

#403 fixed issue setting blackudck pvc sizes
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/containers/pvc_test.go
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/pvc_test.go
Labels: approved, lgtm, size/L

#407 fix operator mod issue
  go.mod
  go.sum
  pkg/opssight/creater_test.go
Labels: approved, lgtm, size/XXL

#410 fix operator-ui dependency issues
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XL

#411 fix password used by postgres user
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/postgres.go
  pkg/apps/blackduck/v1/deployer.go
Labels: approved, lgtm, size/M

#356 Cannot modify storage for Black Duck with Synopsysctl
  go.mod
  go.sum
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
Labels: approved, lgtm, size/M

#383 Synopsysctl mock-kube mode
  go.mod
  pkg/api/types.go
  pkg/apps/alert/alert.go
  pkg/apps/alert/creater_interface.go
  pkg/apps/alert/latest/alert_creater.go
  pkg/apps/alert/latest/alertsecret.go
  pkg/apps/alert/latest/route.go
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/interface.go
  pkg/apps/blackduck/latest/containers/clusterrolebinding.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/latest/init.go
  pkg/apps/blackduck/v1/containers/clusterrolebinding.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v1/init.go
  pkg/opssight/scanner.go
  pkg/soperator/crdVersionMap.go
  pkg/soperator/soperator_components.go
  pkg/soperator/soperator_creater.go
  pkg/soperator/soperator_resources.go
  pkg/soperator/utils.go
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_root.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/prettyprint.go
Labels: approved, lgtm, size/XL

#377 add flags for environs ENABLE_SOURCE_UPLOADS and USE_BINARY_UPLOADS
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/util/helpers_test.go
Labels: approved, lgtm, size/L

#413 allow the user to pass in a file to configure node affinities for blackduck
  examples/deprecated/devNodeAffinityExample.json
  examples/deprecated/nodeAffinityExample.json
  go.mod
  go.sum
  pkg/api/blackduck/v1/types.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/nodeAffinity.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/nodeAffinity.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/crdupdater/deployment.go
  pkg/crdupdater/helpers.go
  pkg/crdupdater/replicationcontroller.go
Labels: approved, lgtm, size/XL

#417 fix a test flake when environs are not in same order
  pkg/blackduck/ctl_blackduck_test.go
Labels: approved, lgtm, size/XS

#390 password migration script
  go.mod
  go.sum
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/M

#418 removed blackduck version from CRD defaults #369
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/M

#422 patch synopsysctl from crashing on update command
  pkg/synopsysctl/cmd_update.go
Labels: approved, size/XS

#420 uncomment opssight creater_test, while removing koki dependency
  go.mod
  go.sum
  pkg/opssight/creater_test.go
Labels: approved, lgtm, size/XL

#380 Make starting the admission webhook listener optional
  cmd/operator/run.go
  pkg/protoform/config.go
  pkg/soperator/soperator_components.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_deploy.go
Labels: approved, lgtm, size/S

#425 synopsysctl checks for cluster clients only when necessary
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/M

#435 remove data field from pvcStructs and uidStructs
  pkg/blackduck/ctl_blackduck.go
Labels: approved, lgtm, size/M

#442 remove typeconversions.go due to the contents no longer being used
  pkg/util/typeconversions.go
Labels: approved, lgtm, size/M

#439 perceptor secret has empty data when creating in kube-mock mode
  pkg/opssight/creater_test.go
  pkg/opssight/perceptor.go
  pkg/opssight/specconfig.go
Labels: approved, lgtm, size/M

#440 tests for MergeEnvMaps in helpers.go
  pkg/util/helpers_test.go
Labels: approved, lgtm, size/M

#448 synopsysctl tests for input through files
  examples/synopsysctl/authCustomCA.txt
  examples/synopsysctl/blackduckExternalHosts.json
  examples/synopsysctl/certificate.txt
  examples/synopsysctl/certificateKey.txt
  examples/synopsysctl/imageGetterSecureRegistries.json
  examples/synopsysctl/imageUIDMap.json
  examples/synopsysctl/nodeAffinity.json
  examples/synopsysctl/proxyCertificate.txt
  examples/synopsysctl/pvc.json
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/creater_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
Labels: approved, lgtm, size/L

#437 Synopsysctl db migrate command and flags
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
Labels: approved, lgtm, size/L

#453 Container Image Tags field self-corrects
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/S

#428 add a smarter check for synopsys operator image version
  go.mod
  go.sum
  pkg/apps/blackduck/latest/containers/creater.go
  pkg/apps/blackduck/v1/containers/creater.go
  pkg/blackduck/util/imageparser.go
  pkg/soperator/crdVersionMap.go
  pkg/soperator/soperator_creater.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/util/imageparser.go
  pkg/util/imageparser_test.go
Labels: approved, lgtm, size/L

#454 Added environ checkboxes in webUI
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/M

#459 Add Start / stop button to the UI #176
  cmd/operator-ui/actions/app.go
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/templates/blackducks/index.html
  cmd/operator-ui/templates/blackducks/show.html
Labels: approved, lgtm, size/M

#457 updating the version label in namespace during upgrade and delete
  go.sum
  pkg/apps/alert/alert.go
  pkg/apps/blackduck/blackduck.go
  pkg/opssight/creater.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: approved, size/L

#460 Namespace scope ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
  go.mod
  go.sum
Labels: approved, size/XXL

#461 fix cluster scope create issue in synopsysctl
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/XS

#464 binary scanner auth fix
  cmd/operator-ui/actions/blackducks.go
  go.mod
  go.sum
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/configmap.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/configmap.go
Labels: approved, lgtm, size/M

#462 Fix synopsysctl cluster scope
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#465 Remove recursive chmod from init containers
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
Labels: approved, lgtm, size/M

#423 more cleanup to synopsysctl messages
  contrib/hydra/pkg/apps/perceivertester/kube.go
  contrib/hydra/pkg/apps/piftester/auxiliaryconfig.go
  contrib/hydra/pkg/apps/piftester/kube.go
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/blackduck/crdinstaller.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/crdupdater/helpers.go
  pkg/crdupdater/route.go
  pkg/opssight/crdinstaller.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/protoform/controller.go
  pkg/soperator/soperator_creater.go
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_root.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/exec_container.go
Labels: approved, size/XL

#466 fix environ bug
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/L

#469 namespace scope ui fix
  Dockerfile
  cmd/operator-ui/actions/app.go
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.sum
  cmd/operator-ui/grifts/init.go
  cmd/operator-ui/main.go
  cmd/operator-ui/package-lock.json
  cmd/operator-ui/templates/blackducks/_form.html
  cmd/operator-ui/templates/blackducks/edit.html
  cmd/operator-ui/templates/blackducks/index.html
  cmd/operator-ui/templates/blackducks/show.html
  pkg/soperator/soperator_resources.go
Labels: approved, size/XXL

#468 Mock Kube Issues - Remove PVCs, Skip Checking BDs in Cluster, Default Version
  pkg/apps/alert/alert.go
  pkg/apps/blackduck/blackduck.go
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/L

#467 update operator fix
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, do-not-merge/hold, size/L

#474 vendor latest operator code in ui
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/L

#475 update default values
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/XS

#478 operator ui vendor fix
  Dockerfile
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/main.go
Labels: approved, lgtm, size/L

#479 [release-2019.6.x] operator ui vendor fix
  Dockerfile
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/main.go
Labels: approved, lgtm, size/L

#477 Attempt to lock dep versions
  cmd/operator-ui/go.mod
  go.mod
Labels: approved, lgtm, size/M

#482 fixed blackduckclient and localFalgs issues
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/L

#483 [release-2019.6.x] fixed blackduckclient and localFalgs issues
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/L

#491 remove-unused-constant
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/XS

#486 Remove bad update sub commands
  examples/synopsysctl/imageUIDMap.json
  examples/upstream/opssight_older_than_hub_500.json
  pkg/api/blackduck/v1/types.go
  pkg/api/blackduck/v1/zz_generated.deepcopy.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/creater.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/creater.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/L

#499 synopsysctl logs don't indicate no errors in cluster
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#498 Remove init containers
  cmd/operator/run.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/postgres.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/database/postgres/postgres.go
  pkg/protoform/config.go
  pkg/util/common.go
  pkg/util/helpers.go
Labels: approved, lgtm, size/XL

#496 [release-2019.6.x] Remove bad update sub commands
  examples/synopsysctl/imageUIDMap.json
  examples/upstream/opssight_older_than_hub_500.json
  pkg/api/blackduck/v1/types.go
  pkg/api/blackduck/v1/zz_generated.deepcopy.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/creater.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/creater.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/L

#485 Check For Synopsys Operator Before Creating
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#501 [release-2019.6.x] Check For Synopsys Operator Before Creating
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#502 cloud build push build.properties version
  cloudbuild.sh
  cloudbuild.yaml
Labels: approved, lgtm, size/M

#503 [release-2019.6.x] cloud build push build.properties version
  cloudbuild.sh
  cloudbuild.yaml
Labels: approved, lgtm, size/M

#500 [release-2019.6.x] synopsysctl logs don't indicate no errors in cluster
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, size/M

#488 synopsysctl gives failed return code #470
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_root.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XL

#504 Use build.properties as default version/image tag
  Makefile
Labels: approved, lgtm, size/S

#506 Remove init containers (#498)
  cmd/operator/run.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/postgres.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/database/postgres/postgres.go
  pkg/protoform/config.go
  pkg/util/common.go
  pkg/util/helpers.go
Labels: approved, lgtm, size/XL

#505 synopsysctl gives failed return code #470 (#488)
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_root.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XL

#495 Fixed issue with creation of output directories generating -p
  Makefile
Labels: approved, lgtm, size/XS

#507 [release-2019.6.x] Fixed issue with creation of output directories generating -p
  Makefile
Labels: approved, lgtm, size/XS

#508 cloud build fix + Rob's version fix in Makefile
  Makefile
  cloudbuild.sh
  cloudbuild.yaml
Labels: approved, lgtm, size/M

#509 cloud build fix in release branch
  cloudbuild.sh
  cloudbuild.yaml
Labels: approved, size/S

#510 cloud build docker fix
  cloudbuild.yaml
Labels: approved, lgtm, size/S

#512 [release-2019.6.x] cloud build docker fix
  cloudbuild.yaml
Labels: approved, lgtm, size/S

#511 deploy multiple operator fix
  pkg/crdupdater/crudcomponents.go
  pkg/opssight/creater.go
  pkg/opssight/plugins.go
  pkg/soperator/soperator_components.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/XL

#494 fix stop button
  cmd/operator-ui/templates/blackducks/index.html
  cmd/operator-ui/templates/blackducks/show.html
Labels: approved, lgtm, size/S

#515 [release-2019.6.x] deploy multiple operator fix
  pkg/crdupdater/crudcomponents.go
  pkg/opssight/creater.go
  pkg/opssight/plugins.go
  pkg/soperator/soperator_components.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/XL

#516 [master] fix stop button
  cmd/operator-ui/templates/blackducks/index.html
  cmd/operator-ui/templates/blackducks/show.html
Labels: approved, lgtm, size/S

#520 prevent the deletion of operator cluster role
  pkg/synopsysctl/cmd_destroy.go
Labels: approved, lgtm, size/XS

#521 [release-2019.6.x] prevent the deletion of operator cluster role
  pkg/synopsysctl/cmd_destroy.go
Labels: approved, lgtm, size/XS

#517 don't print creating when in mock mode
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/L

#523 don't print creating when in mock mode
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/L

#526 fixed removal of exposed issue
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/opssight/specconfig.go
  pkg/soperator/prometheus_resources.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
  pkg/util/crd_defaults.go
  pkg/util/helpers.go
Labels: approved, lgtm, size/L

#528 [release-2019.6.x] fixed removal of exposed issue
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/opssight/specconfig.go
  pkg/soperator/prometheus_resources.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
  pkg/util/crd_defaults.go
  pkg/util/helpers.go
Labels: approved, lgtm, size/L

#527 destroy operator with force option
  pkg/synopsysctl/cmd_destroy.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#531 [release-2019.6.x] destroy operator with force option
  pkg/synopsysctl/cmd_destroy.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#532 Fix makefile environment variables
  Makefile
Labels: approved, lgtm, size/XS

#533 [release-2019.6.x] Fix makefile environment variables
  Makefile
Labels: approved, lgtm, size/XS

#536 fix expose ui in Operator UI and synopsysctl
  Makefile
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
  cmd/operator-ui/templates/blackducks/show.html
  pkg/alert/ctl_alert.go
  pkg/blackduck/ctl_blackduck.go
  pkg/opssight/ctl_opssight.go
Labels: approved, lgtm, size/L

#537 fix expose ui in Operator UI and synopsysctl
  Makefile
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
  cmd/operator-ui/templates/blackducks/show.html
  pkg/alert/ctl_alert.go
  pkg/blackduck/ctl_blackduck.go
  pkg/opssight/ctl_opssight.go
Labels: approved, lgtm, size/M

#542 fix waiting on pods to be running logic
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#546 [release-2019.6.x] fix waiting on pods to be running logic
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#514 change help to addregistry for #493
  pkg/synopsysctl/cmd_update.go
  pkg/util/imageparser.go
  pkg/util/imageparser_test.go
Labels: approved, lgtm, size/L

#543 migrate support
  pkg/alert/crdhandler.go
  pkg/alert/crdinstaller.go
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/creater.go
  pkg/blackduck/crdhandler.go
  pkg/blackduck/crdinstaller.go
  pkg/blackduck/ctl_blackduck.go
  pkg/crdupdater/configmap.go
  pkg/crdupdater/route.go
  pkg/crdupdater/secret.go
  pkg/opssight/crdinstaller.go
  pkg/opssight/handler.go
  pkg/soperator/soperator_creater.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: approved, lgtm, size/XL

#519 check for CRDs and print them in mock mode
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#549 [release-2019.6.x] migrate support
  pkg/alert/crdhandler.go
  pkg/alert/crdinstaller.go
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/creater.go
  pkg/blackduck/crdhandler.go
  pkg/blackduck/crdinstaller.go
  pkg/blackduck/ctl_blackduck.go
  pkg/crdupdater/configmap.go
  pkg/crdupdater/route.go
  pkg/crdupdater/secret.go
  pkg/opssight/crdinstaller.go
  pkg/opssight/handler.go
  pkg/soperator/soperator_creater.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: approved, lgtm, size/XL

#551 [release-2019.6.x] check for CRDs and print them in mock mode
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#552 [release-2019.6.x] change help to addregistry for #493
  pkg/synopsysctl/cmd_update.go
  pkg/util/imageparser.go
  pkg/util/imageparser_test.go
Labels: approved, lgtm, size/L

#530 initial automated testing files
  test-infra/auto-tests/ctl.py
  test-infra/auto-tests/node.json
  test-infra/auto-tests/pytestExamples.py
  test-infra/auto-tests/synopsysresources.py
  test-infra/auto-tests/test_2019_6_0.py
  test-infra/auto-tests/tests_old.py
Labels: approved, lgtm, size/XL

#529 Added db-migrate-mode checkbox to console UI
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/XS

#541 synopsyctl uses subcommands for mock-kube
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/helpers.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/XXL

#553 [release-2019.6.x] Added db-migrate-mode checkbox to console UI
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/XS

#554 synopsysctl uses subcommand native for printing Kubernetes resources
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/helpers.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/XXL

#557 Fixed issues with dependency mismatch
  cmd/operator-ui/go.sum
  go.mod
  go.sum
Labels: approved, size/XS

#558 Fixed issues with dependency mismatch
  cmd/operator-ui/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#447 add bash and zsh completion for synopsysctl
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/synopsysctl/cmd_completion.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_root.go
Labels: approved, lgtm, size/L

#561 fix a few [ that cause completion errors
  pkg/synopsysctl/helpers.go
Labels: approved, lgtm, size/XS

#556 Generate Staged Kube Resources for Black Duck
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/interface.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/L

#562 [release-2019.6.x] Generate Staged Kube Resources for Black Duck
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/interface.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/L

#569 synopsysctl correctly updates operator with cluster scope (567)
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/S

#570 [release-2019.6.x] synopsysctl correctly updates operator with cluster scope (567)
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/S

#571 synopsyctl verifies the --target value is correct
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/helpers.go
Labels: approved, lgtm, size/M

#575 synopsysctl creates mock without being connected to the cluster
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/XS

#572 [release-2019.6.x] synopsyctl verifies the --target value is correct
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/helpers.go
Labels: approved, lgtm, size/M

#573 don't check password in native mode if --output-database is not true
  pkg/blackduck/ctl_blackduck.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#568 Changed synopsysctl to use a standard set of constants for native sub…
  pkg/apps/blackduck/blackduck.go
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#578 [release-2019.6.x] don't check password in native mode if --output-database is not true
  pkg/blackduck/ctl_blackduck.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#580 [release-2019.6.x] Changed synopsysctl to use a standard set of constants for native sub…
  pkg/apps/blackduck/blackduck.go
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#583 Remove namespace, version and images from alert crd default
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/XS

#586 [release-2019.6.x] Remove namespace, version and images from alert crd default
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/XS

#585 Use the namespace in Spec.Namespace instead of the custom resource's ns
  pkg/apps/alert/latest/alertservice.go
  pkg/apps/alert/latest/alertservice_test.go
Labels: approved, lgtm, size/S

#587 [release-2019.6.x] Use the namespace in Spec.Namespace instead of the custom resource's ns
  pkg/apps/alert/latest/alertservice.go
  pkg/apps/alert/latest/alertservice_test.go
Labels: approved, lgtm, size/S

#559 bug fixes
  cmd/operator/run.go
  pkg/alert/crdhandler.go
  pkg/apps/alert/alert.go
  pkg/apps/alert/latest/alert_creater.go
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/blackduck/crdhandler.go
  pkg/crdupdater/crudcomponents.go
  pkg/crdupdater/namespace.go
  pkg/opssight/configmap.go
  pkg/opssight/crdinstaller.go
  pkg/opssight/creater.go
  pkg/opssight/handler.go
  pkg/opssight/perceivers.go
  pkg/opssight/perceptor.go
  pkg/opssight/plugins.go
  pkg/opssight/prometheus.go
  pkg/opssight/scanner.go
  pkg/opssight/skyfire.go
  pkg/opssight/specconfig.go
  pkg/soperator/soperator_creater.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/XXL

#589 [release-2019.6.x] bug fixes
  cmd/operator/run.go
  pkg/alert/crdhandler.go
  pkg/apps/alert/alert.go
  pkg/apps/alert/latest/alert_creater.go
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/blackduck/crdhandler.go
  pkg/crdupdater/crudcomponents.go
  pkg/crdupdater/namespace.go
  pkg/opssight/configmap.go
  pkg/opssight/crdinstaller.go
  pkg/opssight/creater.go
  pkg/opssight/handler.go
  pkg/opssight/perceivers.go
  pkg/opssight/perceptor.go
  pkg/opssight/plugins.go
  pkg/opssight/prometheus.go
  pkg/opssight/scanner.go
  pkg/opssight/skyfire.go
  pkg/opssight/specconfig.go
  pkg/soperator/soperator_creater.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/XXL

#588 synopsyscl can print PVC resources for alert native
  pkg/apps/alert/alert.go
  pkg/apps/alert/creater_interface.go
  pkg/apps/alert/latest/alert_creater.go
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#590 [release-2019.6.x] synopsyscl can print PVC resources for alert native
  pkg/apps/alert/alert.go
  pkg/apps/alert/creater_interface.go
  pkg/apps/alert/latest/alert_creater.go
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#581 will not exit when no kubeconfig found
  pkg/synopsysctl/cmd_root.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/M

#591 [release-2019.6.x] will not exit when no kubeconfig found
  pkg/synopsysctl/cmd_root.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/M

#593 remove namespace ui
  cmd/operator-ui/Makefile
  cmd/operator-ui/actions/app.go
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/config.json
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/index.html
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#595 remove namespace ui
  cmd/operator-ui/Makefile
  cmd/operator-ui/actions/app.go
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/config.json
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/index.html
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#592 Removed license-key, db-prototype, type, and migration-mode from blackduck
  pkg/blackduck/ctl_blackduck.go
Labels: approved, lgtm, size/S

#596 [release-2019.6.x] Removed license-key, db-prototype, type, and migration-mode from blackduck
  pkg/blackduck/ctl_blackduck.go
Labels: approved, lgtm, size/S

#597 Print supported versions when invalid version provided #565
  pkg/apps/alert/alert.go
  pkg/apps/blackduck/blackduck.go
Labels: approved, lgtm, size/XS

#598 [release-2019.6.x] Print supported versions when invalid version provided #565
  pkg/apps/alert/alert.go
  pkg/apps/blackduck/blackduck.go
Labels: approved, lgtm, size/XS

#599 opssight migration issue and removal of UI container
  pkg/opssight/creater.go
  pkg/opssight/perceivers.go
  pkg/opssight/prometheus.go
  pkg/opssight/scanner.go
  pkg/protoform/controller.go
  pkg/soperator/prometheus.go
  pkg/soperator/prometheus_resources.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/L

#600 [release-2019.6.x] opssight migration issue and removal of UI container
  pkg/opssight/creater.go
  pkg/opssight/perceivers.go
  pkg/opssight/prometheus.go
  pkg/opssight/scanner.go
  pkg/protoform/controller.go
  pkg/soperator/prometheus.go
  pkg/soperator/prometheus_resources.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/L

#602 Fix for Liveness probe and app failing inside the operator for the first time
  pkg/crdupdater/deployment.go
  pkg/crdupdater/helpers.go
  pkg/crdupdater/namespace.go
  pkg/crdupdater/replicationcontroller.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#603 [release-2019.6.x] Fix for Liveness probe and app failing inside the operator for the first time
  pkg/crdupdater/deployment.go
  pkg/crdupdater/helpers.go
  pkg/crdupdater/namespace.go
  pkg/crdupdater/replicationcontroller.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#604 namespace scope destroy operator fix
  pkg/synopsysctl/cmd_destroy.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#605 [release-2019.6.x] namespace scope destroy operator fix
  pkg/synopsysctl/cmd_destroy.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#606 pvc migrate fix
  pkg/apps/alert/latest/alertpvc.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/helper.go
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/helper.go
  pkg/apps/blackduck/v1/containers/postgres.go
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#607 [release-2019.6.x] pvc migrate fix
  pkg/apps/alert/latest/alertpvc.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/helper.go
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/helper.go
  pkg/apps/blackduck/v1/containers/postgres.go
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/util/common.go
Labels: approved, lgtm, size/L
