Repository blackducksoftware/synopsys-operator, pull requests merged in 2019-12, with the labels that each got.

#1124 remove prometheus metrics record in opssight
  go.mod
  go.sum
  pkg/opssight/handler.go
  pkg/opssight/metrics.go
  pkg/opssight/metrics_test.go
  pkg/protoform/httpserver.go
Labels: approved, lgtm, size/L

#1123 bumped version for opssight-connector
  pkg/opssight/creater.go
  pkg/opssight/specconfig.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#1125 [master] bumped version for opssight-connector
  pkg/opssight/creater.go
  pkg/opssight/specconfig.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#1127 remove prometheus records for OpsSight
  go.mod
  go.sum
  pkg/opssight/handler.go
  pkg/opssight/metrics.go
  pkg/opssight/metrics_test.go
  pkg/protoform/httpserver.go
Labels: approved, size/L

#1126 create TLS secret for OLM case
  pkg/protoform/controller.go
  pkg/soperator/soperator_components.go
  pkg/soperator/soperator_resources.go
Labels: approved, lgtm, size/S

#1129 convert rc to deployment for Alert and Black Duck resources
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alertdeployment.go
  pkg/apps/alert/latest/cfssldeployment.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v2/containers/authentication.go
  pkg/apps/blackduck/v2/containers/binaryscanner.go
  pkg/apps/blackduck/v2/containers/cfssl.go
  pkg/apps/blackduck/v2/containers/documentation.go
  pkg/apps/blackduck/v2/containers/jobrunner.go
  pkg/apps/blackduck/v2/containers/rabbitmq.go
  pkg/apps/blackduck/v2/containers/registration.go
  pkg/apps/blackduck/v2/containers/scan.go
  pkg/apps/blackduck/v2/containers/solr.go
  pkg/apps/blackduck/v2/containers/uploadcache.go
  pkg/apps/blackduck/v2/containers/webapplogstash.go
  pkg/apps/blackduck/v2/containers/webserver.go
  pkg/apps/blackduck/v2/containers/zookeeper.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/apps/database/postgres/postgres.go
  pkg/crdupdater/replicationcontroller.go
Labels: approved, lgtm, size/L

#1132 [master] create TLS secret for OLM case
  pkg/protoform/controller.go
  pkg/soperator/soperator_components.go
  pkg/soperator/soperator_resources.go
Labels: approved, lgtm, size/S

#1133 [master] convert rc to deployment for Alert and Black Duck resources
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alertdeployment.go
  pkg/apps/alert/latest/cfssldeployment.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v2/containers/authentication.go
  pkg/apps/blackduck/v2/containers/binaryscanner.go
  pkg/apps/blackduck/v2/containers/cfssl.go
  pkg/apps/blackduck/v2/containers/documentation.go
  pkg/apps/blackduck/v2/containers/jobrunner.go
  pkg/apps/blackduck/v2/containers/rabbitmq.go
  pkg/apps/blackduck/v2/containers/registration.go
  pkg/apps/blackduck/v2/containers/scan.go
  pkg/apps/blackduck/v2/containers/solr.go
  pkg/apps/blackduck/v2/containers/uploadcache.go
  pkg/apps/blackduck/v2/containers/webapplogstash.go
  pkg/apps/blackduck/v2/containers/webserver.go
  pkg/apps/blackduck/v2/containers/zookeeper.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/apps/database/postgres/postgres.go
  pkg/crdupdater/replicationcontroller.go
Labels: approved, lgtm, size/L

#1134 [release-2019.11.x] fix memory limits to be expressed as power of two instead of SI unit
  pkg/apps/blackduck/latest/containers/constants.go
  pkg/apps/blackduck/latest/containers/containerflavor.go
  pkg/apps/blackduck/v1/containers/constants.go
  pkg/apps/blackduck/v1/containers/containerflavor.go
  pkg/apps/blackduck/v2/containers/constants.go
  pkg/apps/blackduck/v2/containers/containerflavor.go
Labels: approved, lgtm, size/XL

#1131 get and update master key command changes
  pkg/api/blackduck/v1/types.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/polaris.go
Labels: approved, lgtm, size/L

#1135 [master] get and update master key command changes
  pkg/api/blackduck/v1/types.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/polaris.go
Labels: approved, lgtm, size/L

#1136 add seal key to the ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/L

#1137 [master] add seal key ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, size/M

#1138 crud updater change to fix the memory reflect issue
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v2/creater.go
  pkg/crdupdater/deployment.go
  pkg/crdupdater/replicationcontroller.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#1139 [master] crud updater change to fix the memory reflect issue
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v2/creater.go
  pkg/crdupdater/deployment.go
  pkg/crdupdater/replicationcontroller.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#1141 make seal key mandatory for native mode
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/L

#1142 [master] make seal key mandatory for native mode
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/L

#1143 support for Alert 5.1.0
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, operator, size/XS

#1145 [master] support for Alert 5.1.0
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1146 [saas-2019.11.1] support for Alert 5.1.0
  pkg/apps/alert/latest/alert_versions.go
Labels: size/XS

#1147 fix test for blackduck seal key flag description
  pkg/blackduck/ctl_blackduck_test.go
Labels: approved, size/XS

#1148 [release-2019.11.x] fix test for blackduck seal key flag description
  pkg/blackduck/ctl_blackduck_test.go
Labels: approved, lgtm, size/XS

#1149 Fix clearing environ values
  pkg/blackduck/ctl_blackduck.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/cmd_update_test.go
Labels: approved, lgtm, size/L

#1150 [release-2019.11.x] Fix clearing environ values
  pkg/blackduck/ctl_blackduck.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/cmd_update_test.go
Labels: approved, lgtm, size/L

#1151 [saas-2019.11.1] Fix clearing environ values
  pkg/blackduck/ctl_blackduck.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/cmd_update_test.go
Labels: approved, lgtm, size/L

#1153 vendor operator 2019.12.0 changes
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XS

#1154 [master] vendor operator 2019.12.0 changes
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XS

#1155 update image tags for 12.0 release
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/XS

#1156 [release-2019.12.x] update image tags for 12.0 release
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: size/XS

#1157 update golang version to 13.0 in Makefile to fix build binary
  Makefile
Labels: approved, size/XS

#1159 [release-2019.12.x] update golang version to 13.0 in Makefile to fix build binary
  Makefile
Labels: size/XS

#1160 Set alert deployment strategy to Recreate
  pkg/apps/alert/latest/alertdeployment.go
Labels: approved, size/S

#1161 [release-2019.12.x] Set alert deployment strategy to Recreate
  pkg/apps/alert/latest/alertdeployment.go
Labels: size/S

#1162 [master] Set alert deployment strategy to Recreate
  pkg/apps/alert/latest/alertdeployment.go
Labels: size/S

#1163 update golang verions to 1.13 in Makefile
  Makefile
Labels: approved, size/XS
