Repository blackducksoftware/synopsys-operator, pull requests merged in 2019-10, with the labels that each got.

#927 fix migrate cleanup
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/M

#928 [release-2019.10.x] fix migrate cleanup
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/M

#929 [saas-2019.8.4] fix migrate cleanup
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/M

#930 fix the update binary analysis and source code enabled rc issue
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v2/creater.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#931 [saas-2019.8.4] fix the update binary analysis and source code enabled rc issue
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v2/creater.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#932 [release-2019.10.x] fix the update binary analysis and source code enabled rc issue
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v2/creater.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#923 Validation + --create-organization
  pkg/polaris/polarisMutator.go
  pkg/polaris/polarisProvisionMutator.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_serve_UI.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/polaris.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/L

#938 Add flag to pass GCP service account + more validation
  pkg/polaris/ctl_polaris.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/types.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/L

#949 Fix email validation
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, polaris-operator, size/XS

#940 Improve polaris Validation
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, polaris-operator, size/S

#942 Add get command for polaris
  pkg/synopsysctl/cmd_get.go
Labels: approved, lgtm, polaris-operator, size/M

#950 moved smtp sender email regex replacement to PolarisMutator.go
  pkg/polaris/polarisDBMutator.go
  pkg/polaris/polarisMutator.go
Labels: approved, lgtm, size/XS

#952 fix nil pointer exception when secret/namespace does not exist
  go.mod
  go.sum
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/M

#961 Make the storage class configurable
  pkg/polaris/common_mutator.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/polarisDBMutator.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/polarisProvisionMutator.go
  pkg/polaris/polarisReportingMutator.go
  pkg/polaris/types.go
Labels: approved, lgtm, size/M

#954 Cleanup StatefulSet PVC after deleting polaris.
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, polaris-operator, size/M

#959 Make ingress class configurable
  pkg/polaris/ctl_polaris.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/types.go
Labels: approved, size/XS

#964 Refactor polaris mutators
  pkg/polaris/common_mutator.go
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/patcher.go
  pkg/polaris/polarisDBMutator.go
  pkg/polaris/polarisMutator.go
  pkg/polaris/polarisProvisionMutator.go
  pkg/polaris/polarisReportingMutator.go
  pkg/synopsysctl/polaris.go
Labels: approved, lgtm, size/XXL

#966 Add back NS patcher
  pkg/polaris/patcher.go
Labels: approved, lgtm, polaris-operator, size/S

#969 Fix polaris delete --help
  pkg/synopsysctl/cmd_delete.go
Labels: approved, polaris-operator

#983 encode postgres user and password
  pkg/polaris/patcher.go
Labels: approved, lgtm, size/XS

#988 revert deployment to rc
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/apps/alert/latest/cfsslreplicationcontroller.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v2/containers/authentication.go
  pkg/apps/blackduck/v2/containers/binaryscanner.go
  pkg/apps/blackduck/v2/containers/cfssl.go
  pkg/apps/blackduck/v2/containers/documentation.go
  pkg/apps/blackduck/v2/containers/jobrunner.go
  pkg/apps/blackduck/v2/containers/rabbitmq.go
  pkg/apps/blackduck/v2/containers/registration.go
  pkg/apps/blackduck/v2/containers/scan.go
  pkg/apps/blackduck/v2/containers/solr.go
  pkg/apps/blackduck/v2/containers/uploadcache.go
  pkg/apps/blackduck/v2/containers/webapplogstash.go
  pkg/apps/blackduck/v2/containers/webserver.go
  pkg/apps/blackduck/v2/containers/zookeeper.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/apps/database/postgres/postgres.go
Labels: approved, lgtm, size/L

#989 fix ui service and ui exposed service
  pkg/soperator/soperator_resources.go
Labels: approved, lgtm, size/M

#990 [release-2019.11.x] fix ui service and ui exposed service
  pkg/soperator/soperator_resources.go
Labels: approved, lgtm, size/M

#991 Skip jobs and pvc that already exist
  pkg/synopsysctl/polaris.go
Labels: approved, lgtm, size/M

#992 Make docker registry configurable
  pkg/polaris/ctl_polaris.go
  pkg/polaris/patcher.go
  pkg/polaris/types.go
  pkg/polaris/utils.go
  pkg/synopsysctl/cmd_get.go
Labels: approved, lgtm, size/L

#994 support for Black Duck 2019.10.0
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/S

#995 [release-2019.11.x] support for Black Duck 2019.10.0
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/S

#996 remove download scripts dir
  download/.gitignore
  download/blackduck/args.sh
  download/blackduck/blackduck-images.sh
  download/operator/args.sh
  download/operator/operator-images.sh
  download/opssight/args.sh
  download/opssight/opssight-images.sh
Labels: approved, lgtm, size/XL

#997 [release-2019.11.x] remove download scripts dir
  download/.gitignore
  download/blackduck/args.sh
  download/blackduck/blackduck-images.sh
  download/operator/args.sh
  download/operator/operator-images.sh
  download/opssight/args.sh
  download/opssight/opssight-images.sh
Labels: approved, lgtm, size/XL

#998 Add default values to --help
  pkg/polaris/ctl_polaris.go
Labels: approved, lgtm, polaris-operator, size/S

#999 synopsysctl prints pvc defaults in mock mode
  pkg/blackduck/ctl_blackduck.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#1003 sanity ci against k8s clusters for synopsysctl
  .travis.yml
  go.mod
Labels: approved, size/M

#1009 moved the common stuff to util
  pkg/polaris/creater.go
  pkg/polaris/patcher.go
  pkg/util/baseyamlutil.go
Labels: approved, lgtm, size/L

#1001 [release-2019.11.x] synopsysctl prints pvc defaults in mock mode
  pkg/blackduck/ctl_blackduck.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#1011 [master] [release-2019.11.x] synopsysctl prints pvc defaults in mock mode
  pkg/blackduck/ctl_blackduck.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#1012 fixed secured vulnerabilities
  cmd/operator-ui/yarn.lock
Labels: approved, lgtm, size/XL

#1015 fix security vulnerability
  cmd/operator-ui/yarn.lock
Labels: approved, size/XL

#1016 [release-2019.11.x] fix security vulnerability
  cmd/operator-ui/yarn.lock
Labels: approved, lgtm, size/XL

#1017 fix namespace patch
  pkg/crdupdater/namespace.go
Labels: approved, lgtm, size/XS

#1019 [release-2019.11.x] fix namespace patch
  pkg/crdupdater/namespace.go
Labels: approved, lgtm, size/XS

#1020 [master] fix namespace patch
  pkg/crdupdater/namespace.go
Labels: approved, lgtm, size/XS

#1021 Add version placeholder
  pkg/polaris/patcher.go
Labels: approved, lgtm, size/XS

#1022 [master] Add version placeholder
  pkg/polaris/patcher.go
Labels: approved, lgtm, size/XS

#1024 [master] add tests for different versions of k8s clusters as we…
  .travis.yml
  hack/create_k8s_cluster_and_run_synopsysctl.sh
  hack/test_synopsysctl_native.sh
Labels: approved, lgtm, size/L

#1027 [master] fix app checker docker image sign issue
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/apps/blackduck/latest/deployer.go
Labels: approved, lgtm, size/S

#1026 [release-2019.11.x] fix app checker docker image sign issue
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/apps/blackduck/latest/deployer.go
Labels: approved, lgtm, size/S

#1028 fix operator permission issue
  pkg/crdupdater/crudcomponents.go
  pkg/opssight/creater.go
  pkg/soperator/soperator_creater.go
Labels: approved, lgtm, size/S

#1029 [release-2019.11.x] fix operator permission issue
  pkg/crdupdater/crudcomponents.go
  pkg/opssight/creater.go
  pkg/soperator/soperator_creater.go
Labels: approved, lgtm, size/S

#1030 [master] fix operator permission issue
  pkg/crdupdater/crudcomponents.go
  pkg/opssight/creater.go
  pkg/soperator/soperator_creater.go
Labels: approved, lgtm, size/S

#1032 vendor Black Duck 2019.10.0 changes
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/S

#1036 synopsysctl uses better logic to prioritize environs for Black Duck
  pkg/alert/ctl_alert.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
Labels: approved, lgtm, size/L

#1039 [release-2019.11.x] synopsysctl uses better logic to prioritize environs for Black Duck
  pkg/alert/ctl_alert.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
Labels: approved, lgtm, size/L

#1040 [master] synopsysctl uses better logic to prioritize environs f…
  pkg/alert/ctl_alert.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
Labels: approved, lgtm, size/L

#1041 External DB + ssl conf
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/patcher.go
  pkg/polaris/types.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/polaris.go
Labels: approved, lgtm, size/L

#1043 [master] External DB + ssl conf
  pkg/polaris/creater.go
  pkg/polaris/ctl_polaris.go
  pkg/polaris/patcher.go
  pkg/polaris/types.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/polaris.go
Labels: approved, lgtm, size/L

#1044 Improve help message
  pkg/polaris/ctl_polaris.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/XS

#1045 [master] Improve help message
  pkg/polaris/ctl_polaris.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/XS

#1047 Improve polaris delete
  pkg/polaris/ctl_polaris.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_delete_test.go
Labels: approved, lgtm, size/L

#1048 [master] Synopsysctl kubeconfig issue CLOUD-487
  pkg/synopsysctl/cmd_root.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/L
