Repository blackducksoftware/synopsys-operator, pull requests merged in 2019-08, with the labels that each got.

#712 673 ui clients in deployer
  cmd/operator-ui/actions/app.go
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, size/M

#721 Add delay between CRD and CR creation
  pkg/synopsysctl/cmd_deploy.go
Labels: approved, lgtm, size/S

#719 Add size crd and default sizes during migration
  pkg/apps/store/store.go
  pkg/size/size.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/util/common.go
Labels: approved, lgtm, size/XXL

#728 Add flags to configure registry
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/apps/store/store.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#731 Cherrypick 2019.8.0 changes
  cmd/operator-ui/go.sum
  hack/verify-govet.sh
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/api/alert/v1/types.go
  pkg/api/blackduck/v1/types.go
  pkg/api/blackduck/v1/zz_generated.deepcopy.go
  pkg/api/opssight/v1/types.go
  pkg/api/types.go
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/interface.go
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/containers/pvc_test.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/util/pvc.go
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/pvc_test.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/protoform/controller.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/ctl_interface.go
Labels: approved, lgtm, size/XXL

#735 remove ui dependency
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#732 add files from https://github.com/yashbhutwala/kb-synopsys-operator
  meta-builder/.gitignore
  meta-builder/Dockerfile
  meta-builder/Makefile
  meta-builder/PROJECT
  meta-builder/api/v1/alert_types.go
  meta-builder/api/v1/blackduck_types.go
  meta-builder/api/v1/groupversion_info.go
  meta-builder/api/v1/opssight_types.go
  meta-builder/api/v1/zz_generated.deepcopy.go
  meta-builder/config/certmanager/certificate.yaml
  meta-builder/config/certmanager/kustomization.yaml
  meta-builder/config/certmanager/kustomizeconfig.yaml
  meta-builder/config/crd/bases/synopsys.com_alerts.yaml
  meta-builder/config/crd/kustomization.yaml
  meta-builder/config/crd/kustomizeconfig.yaml
  meta-builder/config/crd/patches/cainjection_in_alerts.yaml
  meta-builder/config/crd/patches/cainjection_in_blackducks.yaml
  meta-builder/config/crd/patches/cainjection_in_opssights.yaml
  meta-builder/config/crd/patches/webhook_in_alerts.yaml
  meta-builder/config/crd/patches/webhook_in_blackducks.yaml
  meta-builder/config/crd/patches/webhook_in_opssights.yaml
  meta-builder/config/default/kustomization.yaml
  meta-builder/config/default/manager_auth_proxy_patch.yaml
  meta-builder/config/default/manager_prometheus_metrics_patch.yaml
  meta-builder/config/default/manager_webhook_patch.yaml
  meta-builder/config/default/webhookcainjection_patch.yaml
  meta-builder/config/manager/kustomization.yaml
  meta-builder/config/manager/manager.yaml
  meta-builder/config/rbac/auth_proxy_role.yaml
  meta-builder/config/rbac/auth_proxy_role_binding.yaml
  meta-builder/config/rbac/auth_proxy_service.yaml
  meta-builder/config/rbac/kustomization.yaml
  meta-builder/config/rbac/leader_election_role.yaml
  meta-builder/config/rbac/leader_election_role_binding.yaml
  meta-builder/config/rbac/role.yaml
  meta-builder/config/rbac/role_binding.yaml
  meta-builder/config/samples/synopsys_v1_alert.yaml
  meta-builder/config/samples/synopsys_v1_blackduck.yaml
  meta-builder/config/samples/synopsys_v1_opssight.yaml
  meta-builder/config/webhook/kustomization.yaml
  meta-builder/config/webhook/kustomizeconfig.yaml
  meta-builder/config/webhook/manifests.yaml
  meta-builder/config/webhook/service.yaml
  meta-builder/controllers/alert_controller.go
  meta-builder/controllers/blackduck_controller.go
  meta-builder/controllers/controllers_utils/create_instruction_manual.go
  meta-builder/controllers/controllers_utils/utils.go
  meta-builder/controllers/controllers_utils/yaml_to_runtime_object_converter.go
  meta-builder/controllers/opssight_controller.go
  meta-builder/controllers/suite_test.go
  meta-builder/flying-dutchman/flying-dutchman.go
  meta-builder/flying-dutchman/instruction_manual.go
  meta-builder/go.mod
  meta-builder/go.sum
  meta-builder/hack/boilerplate.go.txt
  meta-builder/main.go
Labels: approved, do-not-merge/hold, lgtm, size/XXL

#733 move files from https://github.com/yashbhutwala/go-scheduler
  go-scheduler/.gitignore
  go-scheduler/go.mod
  go-scheduler/go.sum
  go-scheduler/scheduler.go
  go-scheduler/scheduler_test.go
  go-scheduler/task.go
  go-scheduler/task_test.go
Labels: approved, lgtm, size/XL

#734 move from https://github.com/yashbhutwala/go-directed-acyclic-graph
  go-directed-acyclic-graph/.gitignore
  go-directed-acyclic-graph/directed_graph.go
  go-directed-acyclic-graph/directed_graph_test.go
  go-directed-acyclic-graph/edge.go
  go-directed-acyclic-graph/go.mod
  go-directed-acyclic-graph/go.sum
  go-directed-acyclic-graph/graph.go
  go-directed-acyclic-graph/graph_test.go
  go-directed-acyclic-graph/node.go
  go-directed-acyclic-graph/output.go
  go-directed-acyclic-graph/output_test.go
  go-directed-acyclic-graph/sort.go
  go-directed-acyclic-graph/sort_test.go
Labels: approved, lgtm, size/XXL

#736 fix go mod and test files
  go.mod
  go.sum
  pkg/apps/alert/latest/alertpvc_test.go
  pkg/apps/alert/latest/alertsecret_test.go
  pkg/apps/alert/latest/alertservice_test.go
Labels: approved, lgtm, size/XXL

#737 make postgres configurable in the UI (#710)
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/XL

#739 Fix how custom resources are accessed following CVE-2019-11247
  pkg/alert/crdhandler.go
  pkg/alert/crdinstaller.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/blackduck/crdhandler.go
  pkg/blackduck/crdinstaller.go
  pkg/opssight/crdinstaller.go
  pkg/opssight/creater.go
  pkg/opssight/handler.go
  pkg/opssight/plugins.go
  pkg/protoform/config.go
  pkg/soperator/soperator_creater.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_db_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: approved, lgtm, size/L

#741 ports commit 770ab19 https://github.com/yashbhutwala/kb-synopsys-operator
  go-directed-acyclic-graph/directed_graph_test.go
  go-directed-acyclic-graph/sort_test.go
  meta-builder/config/crd/bases/synopsys.com_blackducks.yaml
  meta-builder/config/crd/bases/synopsys.com_opssights.yaml
  meta-builder/config/rbac/role.yaml
  meta-builder/config/samples/dependency_sample_alert.yaml
  meta-builder/controllers/alert_controller.go
Labels: approved, lgtm, size/L

#738 opssight registry conf and image-registry support
  go.mod
  go.sum
  pkg/api/alert/v1/types.go
  pkg/api/alert/v1/zz_generated.deepcopy.go
  pkg/api/blackduck/v1/types.go
  pkg/api/blackduck/v1/zz_generated.deepcopy.go
  pkg/api/opssight/v1/types.go
  pkg/api/opssight/v1/zz_generated.deepcopy.go
  pkg/api/types.go
  pkg/apps/util/helper.go
  pkg/blackduck/ctl_blackduck.go
  pkg/opssight/creater_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/opssight/perceivers.go
  pkg/opssight/perceptor.go
  pkg/opssight/prometheus.go
  pkg/opssight/scanner.go
  pkg/opssight/skyfire.go
  pkg/opssight/specconfig.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/XXL

#742 initial alert controller structure
  meta-builder/api/v1/alert_types.go
  meta-builder/api/v1/blackduck_types.go
  meta-builder/api/v1/opssight_types.go
  meta-builder/api/v1/zz_generated.deepcopy.go
  meta-builder/config/crd/bases/synopsys.com_alerts.yaml
  meta-builder/config/samples/alert_runtime_objects.yaml
  meta-builder/config/samples/dependency_sample_alert.yaml
  meta-builder/config/samples/synopsys_v1_alert.yaml
  meta-builder/controllers/alert_controller.go
  meta-builder/controllers/alert_mutator.go
  meta-builder/flying-dutchman/flying-dutchman.go
Labels: approved, lgtm, size/XL

#744 Update UI to not set namespace on custom resources when using cluster…
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XL

#745 add support in alert to have registry configuration and image registry
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/api/alert/v1/types.go
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/apps/alert/latest/cfsslreplicationcontroller.go
Labels: approved, lgtm, size/M

#748 fixed parsing alert issue
  pkg/apps/alert/latest/configmap.go
Labels: approved, lgtm, size/XS

#749 refactor and document the flying dutchman
  meta-builder/api/v1/alert_types.go
  meta-builder/api/v1/blackduck_types.go
  meta-builder/api/v1/opssight_types.go
  meta-builder/config/crd/bases/synopsys.com_alerts.yaml
  meta-builder/controllers/alert_controller.go
  meta-builder/controllers/controllers_utils/create_instruction_manual.go
  meta-builder/flying-dutchman/flying-dutchman.go
  meta-builder/flying-dutchman/instruction_manual.go
Labels: approved, lgtm, size/L

#750 vendor support 2019.8.0 Black Duck app changes to UI
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  pkg/apps/blackduck/latest/containers/webapplogstash.go
Labels: approved, lgtm, size/XL

#753 fix container version
  pkg/apps/blackduck/v2/creater.go
  pkg/apps/blackduck/v2/deployer.go
  pkg/apps/blackduck/v2/init.go
Labels: approved, lgtm, size/S

#751 [master] fixed parsing alert issue
  pkg/apps/alert/latest/configmap.go
Labels: approved, lgtm, size/XS

#754 vendored fix container version ui changes
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XS

#755 fix image pull secret
  pkg/apps/alert/latest/alertreplicationcontroller.go
  pkg/apps/alert/latest/cfsslreplicationcontroller.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/solr.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/binaryscanner.go
  pkg/apps/blackduck/v1/containers/cfssl.go
  pkg/apps/blackduck/v1/containers/documentation.go
  pkg/apps/blackduck/v1/containers/imageTags.go
  pkg/apps/blackduck/v1/containers/jobrunner.go
  pkg/apps/blackduck/v1/containers/rabbitmq.go
  pkg/apps/blackduck/v1/containers/registration.go
  pkg/apps/blackduck/v1/containers/scan.go
  pkg/apps/blackduck/v1/containers/solr.go
  pkg/apps/blackduck/v1/containers/uploadcache.go
  pkg/apps/blackduck/v1/containers/webapplogstash.go
  pkg/apps/blackduck/v1/containers/webserver.go
  pkg/apps/blackduck/v1/containers/zookeeper.go
  pkg/apps/blackduck/v2/containers/authentication.go
  pkg/apps/blackduck/v2/containers/binaryscanner.go
  pkg/apps/blackduck/v2/containers/cfssl.go
  pkg/apps/blackduck/v2/containers/documentation.go
  pkg/apps/blackduck/v2/containers/imageTags.go
  pkg/apps/blackduck/v2/containers/jobrunner.go
  pkg/apps/blackduck/v2/containers/rabbitmq.go
  pkg/apps/blackduck/v2/containers/registration.go
  pkg/apps/blackduck/v2/containers/scan.go
  pkg/apps/blackduck/v2/containers/solr.go
  pkg/apps/blackduck/v2/containers/uploadcache.go
  pkg/apps/blackduck/v2/containers/webapplogstash.go
  pkg/apps/blackduck/v2/containers/webserver.go
  pkg/apps/blackduck/v2/containers/zookeeper.go
  pkg/apps/util/helper.go
  pkg/opssight/perceivers.go
  pkg/opssight/perceptor.go
  pkg/opssight/prometheus.go
  pkg/opssight/scanner.go
  pkg/opssight/skyfire.go
Labels: approved, lgtm, size/L

#740 Make synopsysctl uses the kubeconfig file instead of kubernetes inclu…
  pkg/protoform/kubeconfig.go
  pkg/synopsysctl/utils.go
Labels: approved, lgtm, size/M

#757 Make registry configuration configurable in the UI
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/XL

#759 fix image pull secret postgres
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/v1/containers/postgres.go
  pkg/apps/blackduck/v2/containers/postgres.go
  pkg/apps/database/postgres/postgres.go
Labels: approved, lgtm, size/M

#760 patched version of #758
  meta-builder/PROJECT
  meta-builder/api/v1/alert_types.go
  meta-builder/api/v1/zz_generated.deepcopy.go
  meta-builder/config/crd/bases/synopsys.com_alerts.yaml
  meta-builder/config/samples/dependency_sample_alert.yaml
  meta-builder/config/samples/synopsys_v1_alert.yaml
  meta-builder/controllers/alert_controller.go
  meta-builder/controllers/alert_mutator.go
  meta-builder/controllers/blackduck_controller.go
  meta-builder/controllers/controllers_utils/create_instruction_manual.go
  meta-builder/controllers/opssight_controller.go
  meta-builder/controllers/suite_test.go
  meta-builder/go.mod
  meta-builder/go.sum
  meta-builder/main.go
Labels: approved, lgtm, size/L

#761 add readiness checks for pod, replication controller, service, and pvc
  meta-builder/Makefile
  meta-builder/config/samples/alert_runtime_objects.yaml
  meta-builder/flying-dutchman/flying-dutchman.go
Labels: approved, lgtm, size/M

#763 support for 2019.6.2 Black Duck
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/S

#764 support for 2019.6.2 Black Duck in Operator UI
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, size/L

#762 remove the check for multiple instance of hub in same namespace
  pkg/apps/blackduck/v2/containers/imageTags.go
  pkg/protoform/kubeconfig.go
  pkg/synopsysctl/cmd_create.go
  pkg/util/helpers.go
Labels: approved, lgtm, size/M

#768 add function IsJobFinished
  meta-builder/Makefile
  meta-builder/controllers/alert_controller.go
  meta-builder/controllers/alert_mutator.go
  meta-builder/flying-dutchman/flying-dutchman.go
Labels: approved, lgtm, size/M

#769 remove multiple instance in same namespace check in operator ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, size/M

#770 Fixed crash with synopsysctl deploy --mock #747
  go.sum
  pkg/soperator/soperator_components.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_deploy.go
Labels: approved, lgtm, size/S

#765 Remove RegistryConfiguration namespace field
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/api/types.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/v1/containers/imageTags.go
  pkg/apps/blackduck/v1/containers/postgres.go
  pkg/apps/blackduck/v2/containers/imageTags.go
  pkg/apps/blackduck/v2/containers/postgres.go
  pkg/apps/util/helper.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/L

#775 Remove go.mod for dag and scheduler
  go-directed-acyclic-graph/go.mod
  go-directed-acyclic-graph/go.sum
  go-scheduler/go.mod
  go-scheduler/go.sum
Labels: approved, size/M

#776 Remove registry namespace field from the operator ui
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/L

#778 API and Controller definitions for Polaris and Reporting
  meta-builder/PROJECT
  meta-builder/api/v1/polaris_types.go
  meta-builder/api/v1/polarisdb_types.go
  meta-builder/api/v1/polarisinfra_types.go
  meta-builder/api/v1/reporting_types.go
  meta-builder/api/v1/zz_generated.deepcopy.go
  meta-builder/config/crd/kustomization.yaml
  meta-builder/config/crd/patches/cainjection_in_polaris.yaml
  meta-builder/config/crd/patches/cainjection_in_polarisdbs.yaml
  meta-builder/config/crd/patches/cainjection_in_polarisinfras.yaml
  meta-builder/config/crd/patches/cainjection_in_reportings.yaml
  meta-builder/config/crd/patches/webhook_in_polaris.yaml
  meta-builder/config/crd/patches/webhook_in_polarisdbs.yaml
  meta-builder/config/crd/patches/webhook_in_polarisinfras.yaml
  meta-builder/config/crd/patches/webhook_in_reportings.yaml
  meta-builder/config/samples/dependency_manual_polaris.yaml
  meta-builder/config/samples/dependency_manual_polarisdb.yaml
  meta-builder/config/samples/dependency_manual_reporting.yaml
  meta-builder/config/samples/polaris_runtime_objects.yaml
  meta-builder/config/samples/reporting_runtime_objects.yaml
  meta-builder/config/samples/synopsys_v1_polaris.yaml
  meta-builder/config/samples/synopsys_v1_polarisdb.yaml
  meta-builder/config/samples/synopsys_v1_polarisinfra.yaml
  meta-builder/config/samples/synopsys_v1_reporting.yaml
  meta-builder/controllers/polaris_controller.go
  meta-builder/controllers/polaris_mutator.go
  meta-builder/controllers/polarisdb_controller.go
  meta-builder/controllers/polarisdb_mutator.go
  meta-builder/controllers/polarisinfra_controller.go
  meta-builder/controllers/reporting_controller.go
  meta-builder/controllers/reporting_mutator.go
  meta-builder/controllers/suite_test.go
  meta-builder/go.sum
  meta-builder/main.go
Labels: approved, lgtm, size/XXL

#783 Fix JS exception
  cmd/operator-ui/templates/blackducks/_form.html
Labels: approved, lgtm, size/M

#789 fix security client
  pkg/opssight/crdinstaller.go
Labels: approved, lgtm, size/M

#791 Fix #730
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v2/creater.go
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/XS

#792 Fix #730
  pkg/alert/crdhandler.go
  pkg/synopsysctl/cmd_migrate.go
Labels: approved, lgtm, size/XS

#793 Fix #730
  pkg/soperator/soperator_creater.go
  pkg/soperator/utils.go
Labels: approved, lgtm, size/XS

#794 opssight types
  meta-builder/Makefile
  meta-builder/api/v1/alert_types.go
  meta-builder/api/v1/opssight_types.go
  meta-builder/api/v1/zz_generated.deepcopy.go
  meta-builder/config/crd/bases/synopsys.com_alerts.yaml
  meta-builder/config/crd/bases/synopsys.com_blackducks.yaml
  meta-builder/config/crd/bases/synopsys.com_opssights.yaml
  meta-builder/config/crd/bases/synopsys.com_polaris.yaml
  meta-builder/config/crd/bases/synopsys.com_polarisdbs.yaml
  meta-builder/config/crd/bases/synopsys.com_reportings.yaml
  meta-builder/config/crd/bases/synopsys.com_sizes.yaml
  meta-builder/config/samples/opssight_runtime_objects.yaml
  meta-builder/config/samples/synopsys_v1_opssight.yaml
  meta-builder/controllers/alert_mutator.go
  meta-builder/controllers/opssight_controller.go
  meta-builder/controllers/opssight_mutator.go
Labels: approved, lgtm, size/XXL

#803 Opssight security client
  meta-builder/api/v1/opssight_types.go
  meta-builder/controllers/alert_controller.go
  meta-builder/controllers/opssight_controller.go
  meta-builder/controllers/opssight_mutator.go
  meta-builder/controllers/util/constants.go
  meta-builder/controllers/util/openshift.go
  meta-builder/controllers/util/utils.go
  meta-builder/main.go
Labels: approved, size/L

#806 opssight scanner cluster role and owner label namespace fix
  pkg/opssight/scanner.go
  pkg/soperator/soperator_resources.go
  pkg/util/common.go
Labels: approved, lgtm, size/M

#807 fix deepequal for opssight state
  pkg/opssight/handler.go
Labels: approved, lgtm, size/XS
