Repository blackducksoftware/synopsys-operator, pull requests merged in 2019-05, with the labels that each got.

#254 add rebase plugin to prow and change default lgtm and approval settings
  test-infra/prow/config.yaml
  test-infra/prow/plugins.yaml
Labels: approved, lgtm, size/M

#256 Removed synopsys-operator-ui endpoint in metrics config #251
  pkg/soperator/prometheus_resources.go
Labels: lgtm, size/XS

#255 Removed synopsys-operator-ui endpoint in metrics config #251
  pkg/soperator/prometheus_resources.go
Labels: approved, lgtm, size/XS

#261 OpenShift route and CRUD updater
  pkg/api/types.go
  pkg/apps/alert/alert.go
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alert_creater.go
  pkg/apps/alert/latest/route.go
  pkg/apps/blackduck/latest/containers/route.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/route.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/blackduck/util/helpers.go
  pkg/crdupdater/clusterrole.go
  pkg/crdupdater/clusterrolebinding.go
  pkg/crdupdater/crudcomponents.go
  pkg/crdupdater/helpers.go
  pkg/crdupdater/route.go
  pkg/crdupdater/service.go
  pkg/opssight/creater.go
  pkg/opssight/perceptor.go
  pkg/opssight/prometheus.go
  pkg/opssight/specconfig.go
  pkg/soperator/prometheus.go
  pkg/soperator/prometheus_resources.go
  pkg/soperator/soperator.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
Labels: approved, lgtm, size/XL

#253 Pin to horizon version 0.1.1
  Gopkg.lock
  Gopkg.toml
Labels: lgtm, size/S

#262 Fix for #243 and #244 (#261)
  pkg/api/types.go
  pkg/apps/alert/alert.go
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alert_creater.go
  pkg/apps/alert/latest/route.go
  pkg/apps/blackduck/latest/containers/route.go
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/containers/route.go
  pkg/apps/blackduck/v1/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/blackduck/util/helpers.go
  pkg/crdupdater/clusterrole.go
  pkg/crdupdater/clusterrolebinding.go
  pkg/crdupdater/crudcomponents.go
  pkg/crdupdater/helpers.go
  pkg/crdupdater/route.go
  pkg/crdupdater/service.go
  pkg/opssight/creater.go
  pkg/opssight/perceptor.go
  pkg/opssight/prometheus.go
  pkg/opssight/specconfig.go
  pkg/soperator/prometheus.go
  pkg/soperator/prometheus_resources.go
  pkg/soperator/soperator.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/common.go
Labels: lgtm, size/XL

#263 Renamed opssight flags to use downstream names
  cmd/operator/run.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/L

#264 Renamed opssight flags to use downstream names (#263)
  cmd/operator/run.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/util/crd_defaults.go
Labels: lgtm, size/L

#265 add the cherrypick plugin
  test-infra/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#270 olm cluster role fix
  pkg/apps/blackduck/latest/containers/clusterrolebinding.go
  pkg/apps/blackduck/latest/containers/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/latest/init.go
  pkg/apps/blackduck/v1/containers/clusterrolebinding.go
  pkg/apps/blackduck/v1/containers/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v1/init.go
  pkg/crdupdater/helpers.go
  pkg/opssight/creater.go
  pkg/opssight/creater_test.go
  pkg/opssight/scanner.go
  pkg/opssight/specconfig.go
  pkg/soperator/soperator.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: approved, lgtm, size/XL

#271 olm cluster role and role binding fix #266
  pkg/apps/blackduck/latest/containers/clusterrolebinding.go
  pkg/apps/blackduck/latest/containers/creater.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/latest/init.go
  pkg/apps/blackduck/v1/containers/clusterrolebinding.go
  pkg/apps/blackduck/v1/containers/creater.go
  pkg/apps/blackduck/v1/deployer.go
  pkg/apps/blackduck/v1/init.go
  pkg/crdupdater/helpers.go
  pkg/opssight/creater.go
  pkg/opssight/creater_test.go
  pkg/opssight/scanner.go
  pkg/opssight/specconfig.go
  pkg/soperator/soperator.go
  pkg/soperator/soperator_resources.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: lgtm, size/XL

#272 add OWNERS file for r2d2
  OWNERS
Labels: size/S

#274 added configmap name to opssight defaults
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/XS

#273 include pod filter using labels to support OLM
  pkg/util/common.go
Labels: approved, lgtm, size/S

#277 added configmap name to opssight defaults
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/XS

#279 [release-2019.4.x] include pod filter using labels to support OLM
  pkg/util/common.go
Labels: approved, lgtm, size/S

#285 rename prometheus flags to say metrics instead
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/synopsysctl/cmd_deploy.go
Labels: approved, lgtm, size/M

#289 [release-2019.4.x] rename prometheus flags to say metrics instead
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/synopsysctl/cmd_deploy.go
Labels: size/M

#287 remove flags to configure skyfire #286
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
Labels: approved, lgtm, size/L

#290 [release-2019.4.x] ability to set black duck type in opssight spec #283
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
Labels: approved, lgtm, size/L

#291 remove skyfire flags on release branch
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
Labels: approved, lgtm, size/L

#292 build the operator without ui build
  Dockerfile-Operator
  Makefile
  cmd/operator-ui/package.json
Labels: approved, lgtm, size/M

#294 [release-2019.4.x] build the operator without ui build
  Dockerfile-Operator
  Makefile
  cmd/operator-ui/package.json
Labels: approved, lgtm, size/M

#295 rename opssight parameter for internal registries #293
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
Labels: approved, lgtm, size/XS

#296 [release-2019.4.x] rename opssight parameter for internal registries #293
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
Labels: approved, lgtm, size/XS

#278 crdupdater skips routes if cluster is kubernetes
  pkg/crdupdater/crudcomponents.go
  pkg/crdupdater/route.go
  pkg/crdupdater/updater.go
  pkg/soperator/soperator.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/util/common.go
Labels: approved, lgtm, size/S

#297 [release-2019.4.x] crdupdater skips routes if cluster is kubernetes
  pkg/crdupdater/crudcomponents.go
  pkg/crdupdater/route.go
  pkg/crdupdater/updater.go
  pkg/soperator/soperator.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/util/common.go
Labels: approved, lgtm, size/S

#298 create the operator and prometheus configmap if not exist
  pkg/protoform/config.go
  pkg/protoform/controller.go
Labels: approved, lgtm, size/M

#299 [release-2019.4.x] create the operator and prometheus configmap if not exist
  pkg/protoform/config.go
  pkg/protoform/controller.go
Labels: approved, lgtm, size/M

#302 Fixed issues launching the image-processor #301
  pkg/soperator/soperator_resources.go
Labels: approved, lgtm, size/XS

#280 add cherrypick pod to the prow cluster
  test-infra/prow/cluster.yaml
  test-infra/prow/plugins.yaml
Labels: approved, lgtm, size/M

#304 Removed api group for images
  pkg/opssight/perceivers.go
Labels: approved, lgtm, size/XS

#305 [release-2019.4.x] Removed api group for images
  pkg/opssight/perceivers.go
Labels: approved, lgtm, size/XS

#306 merge boolean fix
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/synopsysctl/cmd_create.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/S

#307 [release-2019.4.x] merge boolean fix
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/synopsysctl/cmd_create.go
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/S

#308 set the desired state to start
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/XS

#309 [release-2019.4.x] set the desired state to start
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/XS

#310 break up prow's cluster configuration into its components
  test-infra/prow/Makefile
  test-infra/prow/cherrypick.yaml
  test-infra/prow/cluster.yaml
  test-infra/prow/deck.yaml
  test-infra/prow/deck_rbac.yaml
  test-infra/prow/hook.yaml
  test-infra/prow/hook_rbac.yaml
  test-infra/prow/horologium.yaml
  test-infra/prow/horologium_rbac.yaml
  test-infra/prow/needs_rebase.yaml
  test-infra/prow/plank.yaml
  test-infra/prow/plank_rbac.yaml
  test-infra/prow/prow_crd.yaml
  test-infra/prow/prow_misc.yaml
  test-infra/prow/sinker.yaml
  test-infra/prow/sinker_rbac.yaml
  test-infra/prow/statusreconciler.yaml
  test-infra/prow/statusreconciler_rbac.yaml
  test-infra/prow/tide.yaml
  test-infra/prow/tide_rbac.yaml
Labels: approved, lgtm, size/XXL

#314 Fix #313
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
Labels: approved, lgtm, size/XS

#315 [release-2019.4.x] Fix #313
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
Labels: approved, lgtm, size/XS

#317 Do not assign a version label to postgres components
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/v1/containers/postgres.go
Labels: approved, lgtm, size/XS

#318 [release-2019.4.x] Do not assign a version label to postgres components
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/v1/containers/postgres.go
Labels: approved, lgtm, size/XS

#321 Add support for Blackduck 2019.4.2
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/S

#322 [release-2019.4.x] Add support for Blackduck 2019.4.2
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/S

#324 buffalo build dep and default cert fix
  Dockerfile
  Makefile
  cloudbuild.yaml
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/deployer.go
Labels: approved, lgtm, size/S

#325 [release-2019.4.x] buffalo build dep and default cert fix
  Dockerfile
  Makefile
  cloudbuild.yaml
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/deployer.go
Labels: approved, lgtm, size/S

#327 Use the certificate and key if provided in the custom resource regardless of Spec.CertificateName
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/deployer.go
Labels: approved, lgtm, size/M

#328 [release-2019.4.x] Use the certificate and key if provided in the custom resource regardless of Spec.CertificateName
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/deployer.go
Labels: approved, lgtm, size/M

#337 Change default version to 2019.4.2
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/S

#338 [release-2019.4.x] Change default version to 2019.4.2
  pkg/util/crd_defaults.go
Labels: approved, lgtm, size/S

#336 change synopsysctl to default to latest operator image version
  pkg/synopsysctl/cmd_deploy.go
Labels: approved, lgtm, size/XS

#340 synopsysctl deploys master operator image from gcr
  pkg/synopsysctl/cmd_deploy.go
Labels: approved, lgtm, size/XS

#342 Point Fix GetRouteClient Error Checking
  pkg/util/common.go
Labels: approved, lgtm, size/S

#344 [master] Point Fix GetRouteClient Error Checking
  pkg/util/common.go
Labels: approved, lgtm, size/S

#347 Collect the name of the persistent volumes even if the PVC is not listed in Spec.PVC
  pkg/apps/blackduck/latest/creater.go
  pkg/apps/blackduck/v1/creater.go
Labels: approved, lgtm, operator, size/S

#350 use the correct password for user of external db
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/deployer.go
Labels: approved, lgtm, operator, size/XS

#351 [master] use the correct password for user of external db
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/deployer.go
Labels: approved, lgtm, size/XS

#352 Deploy a service account and clusterrolebinding even if BDBA is disabled
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/deployer.go
Labels: approved, lgtm, size/M

#353 [release-2019.4.x] Deploy a service account and clusterrolebinding even if BDBA is disabled
  pkg/apps/blackduck/latest/deployer.go
  pkg/apps/blackduck/v1/deployer.go
Labels: approved, lgtm, size/M

#364 Print kubernetes and openshift version during startup
  cmd/operator/run.go
  pkg/util/common.go
Labels: approved, lgtm

#346 Synopsysctl Test - compare flag name with name used to set the spec
  pkg/alert/ctl_alert_test.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
Labels: approved, lgtm, size/M

#355 fix issue #282 to delete multiple resources
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_get.go
Labels: approved, size/M

#367 Change the mode used for secret volumes
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/v1/containers/authentication.go
  pkg/apps/blackduck/v1/containers/webserver.go
Labels: approved, lgtm, size/S

#370 remove scan-type flag from synopsysctl create blackduck
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
Labels: approved, lgtm, size/S

#374 Hub db migration
  pkg/apps/blackduck/latest/creater.go
  pkg/blackduck/crdhandler.go
Labels: approved, lgtm, size/M

#378 synopsysctl can use environ KUBECONFIG
  pkg/synopsysctl/cmd_root.go
Labels: approved, lgtm, size/XS

#373 removed template value for the --template flag for all resources
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#362 Edit only activates editor, moved edit sub-commands into update
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, size/XL

#372 move globals and constants into one file, and add version to synopsysctl
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_root.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/constants.go
Labels: approved, size/L

#382 add flag for postgres PVC size
  pkg/alert/ctl_alert_test.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight_test.go
Labels: approved, size/L

#385 Edit bash commands to use && where applicable
  Makefile
Labels: approved, lgtm, size/S

#387 go mods ui fix
  Dockerfile
  cmd/operator-ui/actions/app.go
  cmd/operator-ui/actions/render.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
  cmd/operator-ui/package-lock.json
  cmd/operator-ui/package.json
  cmd/operator-ui/yarn.lock
  go.mod
  go.sum
Labels: approved, lgtm, size/XXL

#357 Add start and stop options for blackduck in scope of issue #354
  cmd/operator-ui/templates/blackducks/_form.html
  examples/deprecated/opssight.json
  examples/upstream/opssight.json
  pkg/alert/crdhandler.go
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/apps/alert/latest/alert_creater.go
  pkg/blackduck/crdhandler.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/handler.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/util/crd_defaults.go
Labels: approved, size/XL

#388 Synopsysctl help clean up
  .github/ISSUE_TEMPLATE/bug_report.md
  Dockerfile
  Dockerfile-Operator
  README.md
  cmd/synopsysctl/README.md
  go.sum
  help.1
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/apps/app.go
  pkg/apps/blackduck/latest/deployer.go
  pkg/blackduck/ctl_blackduck.go
  pkg/blackduck/ctl_blackduck_test.go
  pkg/opssight/ctl_opssight.go
  pkg/opssight/ctl_opssight_test.go
  pkg/soperator/ctl_soperator.go
  pkg/soperator/soperator.go
  pkg/soperator/soperator_resources.go
  pkg/soperator/utils.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_deploy.go
  pkg/synopsysctl/cmd_describe.go
  pkg/synopsysctl/cmd_destroy.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_root.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/constants.go
  pkg/synopsysctl/utils.go
  pkg/util/common.go
Labels: approved, size/XXL

#392 fixed issue setting blackudck pvc sizes
  pkg/apps/blackduck/latest/containers/pvc.go
  pkg/apps/blackduck/latest/containers/pvc_test.go
Labels: approved, lgtm, size/L

#394 fixed pvc issue for black duck version v1
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/pvc_test.go
Labels: approved, lgtm, size/L

#395 Revert "fixed pvc issue for black duck version v1"
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/pvc_test.go
Labels: approved, size/L

#397 fixed pvc issue for black duck version v1
  pkg/apps/blackduck/v1/containers/pvc.go
  pkg/apps/blackduck/v1/containers/pvc_test.go
Labels: approved, lgtm, size/L

#399 support for 2019.4.3
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/util/crd_defaults.go
Labels: approved, size/M

#400 [release-2019.4.x] support for 2019.4.3
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/util/crd_defaults.go
Labels: size/M

#401 change to 2019.4.2
  pkg/synopsysctl/cmd_deploy.go
Labels: approved, size/XS
