Repository blackducksoftware/synopsys-operator, pull requests merged in 2020-01, with the labels that each got.

#1164 add recreate strategy to cfssl deployment for alert
  pkg/apps/alert/latest/cfssldeployment.go
Labels: approved, size/S

#1165 [release-2019.12.x] add recreate strategy to cfssl deployment for alert
  pkg/apps/alert/latest/cfssldeployment.go
Labels: approved, lgtm, size/S

#1166 [master] add recreate strategy to cfssl deployment for alert
  pkg/apps/alert/latest/cfssldeployment.go
Labels: size/S

#1167 [release-2019.12.x] disable the UI for the 2019.12.0 synopsysctl release
  pkg/synopsysctl/cmd_serve_UI.go
Labels: approved, lgtm, size/S

#1168 disable ability to set securityContexts for Alert for 12.0 release
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/api/alert/v1/types.go
  pkg/apps/alert/latest/alertdeployment.go
  pkg/apps/alert/latest/cfssldeployment.go
Labels: approved, lgtm, size/L

#1170 [master] disable ability to set securityContexts for Alert for 12.0 release
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/api/alert/v1/types.go
  pkg/apps/alert/latest/alertdeployment.go
  pkg/apps/alert/latest/cfssldeployment.go
Labels: approved, lgtm, size/L

#1171 [release-2019.12.x] Fix upgrade bd group ownership
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/cmd_update_test.go
Labels: approved, lgtm, size/M

#1174 better pvc json file example
  examples/synopsysctl/pvc.json
Labels: approved, lgtm, size/M

#1175 [master] better pvc json file example
  examples/synopsysctl/pvc.json
Labels: approved, lgtm, size/M

#1173 Remove setting default value to 1000 and rename uploadcache security …
  examples/synopsysctl/securityContext.json
  pkg/apps/alert/latest/alertdeployment.go
  pkg/apps/alert/latest/cfssldeployment.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/database/postgres/postgres.go
  pkg/apps/util/helper.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#1176 [master] Remove setting default value to 1000 and rename uploadcache security …
  examples/synopsysctl/securityContext.json
  pkg/apps/alert/latest/alertdeployment.go
  pkg/apps/alert/latest/cfssldeployment.go
  pkg/apps/blackduck/latest/containers/authentication.go
  pkg/apps/blackduck/latest/containers/binaryscanner.go
  pkg/apps/blackduck/latest/containers/cfssl.go
  pkg/apps/blackduck/latest/containers/documentation.go
  pkg/apps/blackduck/latest/containers/jobrunner.go
  pkg/apps/blackduck/latest/containers/postgres.go
  pkg/apps/blackduck/latest/containers/rabbitmq.go
  pkg/apps/blackduck/latest/containers/registration.go
  pkg/apps/blackduck/latest/containers/scan.go
  pkg/apps/blackduck/latest/containers/uploadcache.go
  pkg/apps/blackduck/latest/containers/webapplogstash.go
  pkg/apps/blackduck/latest/containers/webserver.go
  pkg/apps/blackduck/latest/containers/zookeeper.go
  pkg/apps/database/postgres/postgres.go
  pkg/apps/util/helper.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#1177 Fix blackduck pvc test
  pkg/blackduck/ctl_blackduck_test.go
Labels: approved, do-not-merge/hold, size/S

#1178 [master] Fix blackduck pvc test
  pkg/blackduck/ctl_blackduck_test.go
Labels: approved, lgtm, size/S

#1179 Change Volume File Ownership Jobs for Security Contexts
  pkg/synopsysctl/cmd_update.go
  pkg/util/security_context.go
Labels: approved, lgtm, size/L

#1181 prevent setting security contexts when in openshift
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#1180 [master] Change Volume File Ownership Jobs for Security Contexts
  pkg/synopsysctl/cmd_update.go
  pkg/util/security_context.go
Labels: approved, lgtm, size/L

#1183 [master] prevent setting security contexts when in openshift
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#1184 add quickstart instructions
  README.md
Labels: approved, lgtm, size/S

#1185 Fix Openshift security context check in Native Mode
  pkg/synopsysctl/cmd_create.go
Labels: approved, size/XS

#1188 restart pods for all security context changes (unless during upgrade)
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#1186 [master] Fix Openshift security context check in Native Mode
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/XS

#1187 Add support for 10.2 + backport Alert fix to SaaS version
  build.properties
  go.mod
  go.sum
  pkg/apps/alert/latest/alertdeployment.go
  pkg/apps/alert/latest/cfssldeployment.go
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/M

#1189 [master] restart pods for all security context changes (unless during upgrade)
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/M

#1190 Add Support for 10.2 Black Duck
  pkg/apps/blackduck/v3/containers/imageTags.go
Labels: approved, lgtm, size/S

#1191 [master] Add Support for 10.2 Black Duck
  pkg/apps/blackduck/v3/containers/imageTags.go
Labels: approved, lgtm, size/S

#1192 Security context Ownership Jobs For Native
  examples/synopsysctl/ownershipjobs.yaml
Labels: approved, size/L

#1193 [master] Security context Ownership Jobs For Native
  examples/synopsysctl/ownershipjobs.yaml
Labels: size/L

#1194 fix imageTags for Black Duck 2019.10.2 from 10.1 to 10.2
  pkg/apps/blackduck/v3/containers/imageTags.go
Labels: approved, lgtm, size/S

#1195 [master] fix imageTags for Black Duck 2019.10.2 from 10.1 to 10.2
  pkg/apps/blackduck/v3/containers/imageTags.go
Labels: size/S

#1196 add storageClass and volumeName to the example pvc.json file
  examples/synopsysctl/pvc.json
  go.mod
  go.sum
  pkg/blackduck/ctl_blackduck_test.go
Labels: approved, size/M

#1198 saas size
  pkg/apps/blackduck/latest/containers/constants.go
  pkg/apps/blackduck/v1/containers/constants.go
  pkg/apps/blackduck/v2/containers/constants.go
Labels: approved, size/M

#1201 added support for Black Duck 2019.12.1
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#1202 [master] added support for Black Duck 2019.12.1
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#1203 [saas-2019.12.1] added support for Black Duck 2019.12.1
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S
