Repository blackducksoftware/synopsys-operator, pull requests merged in 2020-03, with the labels that each got.

#1275 move SetHelmValuesMap function into common util folder
  pkg/polaris-reporting/ctl_polarisreporting.go
  pkg/polaris-reporting/helpers.go
  pkg/polaris-reporting/helpers_test.go
  pkg/util/helm_helpers.go
Labels: approved, size/L

#1274 Fix mock printing PVCs due to reading PVC file twice
  pkg/apps/blackduck/util/pvc.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/XS

#1278 added support for Alert 5.2.3
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1280 added support for Black Duck 2020.2.1
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#1281 [release-2020.2.x] Fix mock printing PVCs due to reading PVC file twice
  pkg/apps/blackduck/util/pvc.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/XS

#1282 [master] added support for Alert 5.2.3
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1283 [master] added support for Black Duck 2020.2.1
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#1276 Add test file for Helm Flag Mapper
  pkg/util/helm_helpers_test.go
Labels: approved, lgtm, size/L

#1284 vendor Black Duck 2020.2.1 to operator ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XXL

#1285 vendor Black Duck 2020.2.1 support to operator ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XXL

#1286 [saas-2020.2.1] added support for Alert 5.2.3
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1288 Missing namespace in helm clients
  pkg/util/helm_helpers.go
Labels: approved, lgtm, size/XS

#1287 only require postgres-host/username if using external postgres
  pkg/polaris-reporting/ctl_polarisreporting.go
Labels: approved, lgtm, size/S

#1290 add back build and test to travis; fix typo
  .travis.yml
  pkg/polaris-reporting/ctl_polarisreporting.go
  pkg/synopsysctl/cmd_create_test.go
Labels: approved, size/S

#1291 removed deprecated desired-state flag from alert
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
Labels: approved, lgtm, size/S

#1295 Support Alert 5.0.3
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1296 feat: merged GenerateHelmFlagsFromCobraFlags and AddHelmValueByCobraFlag method
  pkg/polaris/ctl_polaris.go
Labels: approved, lgtm, size/L

#1299 [saas-2020.2.2] added support for Black Duck 2020.2.1
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#1300 [saas-2020.2.2] vendor Black Duck 2020.2.1 to operator ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XXL

#1301 [saas-2020.2.2] [release-2020.2.x] Fix mock printing PVCs due to reading PVC file twice
  pkg/apps/blackduck/util/pvc.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/XS

#1303 rename from minio to polaris-helmchart-minio
  pkg/polaris/ctl_polaris.go
Labels: approved, lgtm, size/XS

#1302 support for alert 5.3.0 with synopsys-operator
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1305 fix link for polaris to point to polaris docs instead of polaris-reporting
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS
