Repository blackducksoftware/synopsys-operator, pull requests merged in 2020-04, with the labels that each got.

#1307 updated the correct version of nginx and upload cache for Black Duck 2020.2.1
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/XS

#1308 [develop] updated the correct version of nginx and upload cache for Black Duck 2020.2.1
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/XS

#1304 fix helm upgrade with new version of charts
  pkg/polaris-reporting/ctl_polarisreporting.go
  pkg/polaris/ctl_polaris.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/helm_helpers.go
Labels: approved, lgtm, size/M

#1309 [release-2020.2.x] Support Alert 5.0.3
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1310 [release-2020.2.x] support for alert 5.3.0 with synopsys-operator
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1313 [saas-2020.2.3] updated the correct version of nginx and upload cache for Black Duck 2020.2.1
  pkg/apps/blackduck/latest/containers/imageTags.go
Labels: approved, lgtm, size/XS

#1314 [saas-2020.2.3] [release-2020.2.x] Support Alert 5.0.3
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1315 [saas-2020.2.3] [release-2020.2.x] support for alert 5.3.0 with synopsys-operator
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1316 work around to fix the report storage chart issue
  pkg/polaris-reporting/ctl_polarisreporting.go
Labels: approved, lgtm, size/XS

#1317 fix for bdba upgrade scenario
  pkg/bdba/ctl_bdba.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, size/M

#1262 CRUD with BDBA Helm Chart
  pkg/bdba/ctl_bdba.go
  pkg/bdba/ctl_bdba_test.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/XL

#1318 fix bad error from missing release
  pkg/util/helm_helpers.go
Labels: approved, lgtm, size/S

#1319 [develop] fix bad error from missing release
  pkg/util/helm_helpers.go
Labels: approved, lgtm, size/S

#1321 CRUD tweaks to help messages and required flags
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
Labels: approved, size/L

#1298 CRUD with Alert Helm Chart and Alert Migration from Operator to Helm
  cmd/operator/run.go
  pkg/alert/crdcontroller.go
  pkg/alert/crdhandler.go
  pkg/alert/crdinstaller.go
  pkg/alert/creater.go
  pkg/alert/ctl_alert.go
  pkg/alert/ctl_alert_test.go
  pkg/apps/alert/alert.go
  pkg/apps/alert/common/serviceaccount.go
  pkg/apps/alert/creater_interface.go
  pkg/apps/alert/latest/alert_components.go
  pkg/apps/alert/latest/alert_creater.go
  pkg/apps/alert/latest/alert_versions.go
  pkg/apps/alert/latest/alertcertificatesecret.go
  pkg/apps/alert/latest/alertdeployment.go
  pkg/apps/alert/latest/alertpvc.go
  pkg/apps/alert/latest/alertpvc_test.go
  pkg/apps/alert/latest/alertsecret.go
  pkg/apps/alert/latest/alertsecret_test.go
  pkg/apps/alert/latest/alertservice.go
  pkg/apps/alert/latest/alertservice_test.go
  pkg/apps/alert/latest/cfssldeployment.go
  pkg/apps/alert/latest/cfsslservice.go
  pkg/apps/alert/latest/configmap.go
  pkg/apps/alert/latest/label.go
  pkg/apps/alert/latest/route.go
  pkg/apps/alert/latest/serviceaccount.go
  pkg/apps/app.go
  pkg/synopsysctl/CRDPrint.go
  pkg/synopsysctl/alert_migrate.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_edit.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_migrate.go
  pkg/synopsysctl/cmd_start.go
  pkg/synopsysctl/cmd_stop.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/constants.go
  pkg/util/helm_helpers.go
  pkg/util/helm_helpers_test.go
Labels: approved, lgtm, size/XXL

#1324 Check if a release exists before creating the resource
  pkg/util/helm_helpers.go
Labels: approved, lgtm, size/S

#1323 Fix secret names
  pkg/blackduck/certificate.go
  pkg/blackduck/conversion.go
  pkg/synopsysctl/blackduck_migrate.go
  pkg/synopsysctl/cmd_delete.go
  pkg/util/helm_helpers.go
Labels: approved, size/M

#1325 add postfix to alert to fix for multiple apps using same name within same namespace
  Makefile
  pkg/alert/ctl_alert.go
  pkg/synopsysctl/alert_migrate.go
  pkg/synopsysctl/blackduck_migrate.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_get.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/constants.go
Labels: approved, size/M

#1328 set default values for black duck with helm
  pkg/blackduck/ctl_blackduck.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#1327 Helmchart standalone debug
  pkg/alert/ctl_alert.go
  pkg/synopsysctl/alert_migrate.go
Labels: approved, lgtm, size/M

#1329 fix init labels
  pkg/synopsysctl/alert_migrate.go
Labels: approved, size/S

#1330 fix an echo statement in Makefile
  Makefile
Labels: approved
