Repository blackducksoftware/synopsys-operator, pull requests merged in 2020-02, with the labels that each got.

#1204 vendor operator 2019.12.1 to operator ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XS

#1205 [saas-2019.12.1] vendor operator 2019.12.1 to operator ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XS

#1206 [master] vendor operator 2019.12.1 to operator ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/XS

#1208 add support to Black Duck 2020.2.0
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#1209 vendor operator 2020.2.0 changes to ui
  cmd/operator-ui/go.mod
Labels: approved, lgtm, size/XS

#1210 revoke the access of st schema to blackduck_reporter
  pkg/apps/blackduck/latest/databaseinit.go
Labels: approved, lgtm, size/XS

#1211 [saas-2019.12.1] revoke the access of st schema to blackduck_reporter
  pkg/apps/blackduck/latest/databaseinit.go
Labels: approved, lgtm, size/XS

#1212 [master] revoke the access of st schema to blackduck_reporter
  pkg/apps/blackduck/latest/databaseinit.go
Labels: approved, lgtm, size/XS

#1214 revert Black Duck 2019.12.1 change and add support for Black Duck 2019.10.3
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/apps/blackduck/v3/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#1215 [saas-2019.12.1] revert Black Duck 2019.12.1 change and add support for Black Duck 2019.10.3
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/apps/blackduck/v3/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/M

#1216 vendor operator Black Duck 2019.10.3 changes to ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
Labels: approved, lgtm, size/XS

#1217 [saas-2019.12.1] vendor operator Black Duck 2019.10.3 changes to ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
Labels: approved, lgtm, size/XS

#1218 add environ that specifies the type of cluster the app is in
  pkg/apps/blackduck/latest/containers/configmap.go
Labels: approved, lgtm, size/XS

#1219 [master] add environ that specifies the type of cluster the app is in
  pkg/apps/blackduck/latest/containers/configmap.go
Labels: approved, lgtm, size/XS

#1224 Support for Alert 5.2.0
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1225 added support for Black Duck 2019.10.3
  pkg/apps/blackduck/v3/containers/imageTags.go
Labels: approved, lgtm, size/S

#1223 Support for blackduck 2019.12.1
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#1228 [master] added support for Black Duck 2019.10.3
  pkg/apps/blackduck/v3/containers/imageTags.go
Labels: approved, lgtm, size/S

#1229 [master] Support for Alert 5.2.0
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1230 [release-2020.2.x] Support for Alert 5.2.0
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1213 Use helm 3 to deploy Polaris-Reporting
  pkg/polaris-reporting/creater.go
  pkg/polaris-reporting/ctl_polarisreporting.go
  pkg/polaris-reporting/types.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/constants.go
  pkg/synopsysctl/helpers.go
  pkg/synopsysctl/utils.go
  pkg/util/helm_helpers.go
Labels: approved, size/XL

#1231 [release-2020.2.x] Use helm 3 to deploy Polaris-Reporting
  pkg/polaris-reporting/creater.go
  pkg/polaris-reporting/ctl_polarisreporting.go
  pkg/polaris-reporting/types.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/constants.go
  pkg/synopsysctl/helpers.go
  pkg/synopsysctl/utils.go
  pkg/util/helm_helpers.go
Labels: size/XL

#1227 Enable saml signature verification by default
  pkg/apps/blackduck/latest/containers/configmap.go
  pkg/apps/blackduck/latest/containers/environs.go
  pkg/util/helpers.go
Labels: approved, do-not-merge/hold, size/S

#1238 vendor operator 2020.2.0-saml-verification changes
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm

#1240 Enable saml signature verification by default (#1227)
  pkg/apps/blackduck/latest/containers/configmap.go
  pkg/apps/blackduck/latest/containers/environs.go
  pkg/util/helpers.go
Labels: approved, lgtm, size/M

#1234 Vendor helm3 api
  go.mod
  go.sum
  pkg/alert/client/clientset/versioned/typed/alert/v1/alert_client.go
  pkg/blackduck/client/clientset/versioned/typed/blackduck/v1/blackduck_client.go
  pkg/opssight/client/clientset/versioned/typed/opssight/v1/opssight_client.go
  pkg/polaris-reporting/ctl_polarisreporting.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/helm_helpers.go
Labels: approved, size/XXL

#1241 support for Black Duck 2020.2.0 in operator ui
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/S

#1243 [master] Vendor helm3 api
  go.mod
  go.sum
  pkg/alert/client/clientset/versioned/typed/alert/v1/alert_client.go
  pkg/blackduck/client/clientset/versioned/typed/blackduck/v1/blackduck_client.go
  pkg/opssight/client/clientset/versioned/typed/opssight/v1/opssight_client.go
  pkg/polaris-reporting/ctl_polarisreporting.go
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_update.go
  pkg/util/helm_helpers.go
Labels: approved, lgtm, size/XXL

#1244 [saas-2019.12.2] Support for Alert 5.2.0
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1245 [saas-2019.12.2] Support for blackduck 2019.12.1
  pkg/apps/blackduck/blackduck.go
  pkg/apps/blackduck/latest/containers/imageTags.go
  pkg/synopsysctl/cmd_create.go
Labels: approved, lgtm, size/S

#1246 [saas-2019.12.2] Enable saml signature verification by default (#1227)
  pkg/apps/blackduck/latest/containers/configmap.go
  pkg/apps/blackduck/latest/containers/environs.go
  pkg/util/helpers.go
Labels: approved, lgtm, size/M

#1247 [saas-2019.12.2] vendor operator 2019.12.2 operator code for saml verification
  cmd/operator-ui/actions/blackducks.go
  cmd/operator-ui/go.mod
  cmd/operator-ui/go.sum
Labels: approved, lgtm, size/S

#1242 support alert 5.0.2 and 5.2.1
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1248 [master] support alert 5.0.2 and 5.2.1
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1249 updated helm vendor to 3.1.1 from rc
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#1251 fix the update help page to clearly show polaris-reporting
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#1254 smtp value settings change for polaris reporting
  pkg/polaris-reporting/ctl_polarisreporting.go
Labels: approved, lgtm, size/L

#1256 [master] smtp value settings change for polaris reporting
  pkg/polaris-reporting/ctl_polarisreporting.go
Labels: approved, lgtm, size/L

#1255 BDRELENG-1649 - Add new build target for running Coverity scans
  Makefile
Labels: approved, lgtm, size/S

#1259 [release-2020.2.x] BDRELENG-1649 - Add new build target for running Coverity scans
  Makefile
Labels: approved, lgtm, size/S

#1258 [master] BDRELENG-1649 - Add new build target for running Coverity scans
  Makefile
Labels: approved, lgtm, size/S

#1250 [master] updated helm vendor to 3.1.1 from rc
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#1252 [master] fix the update help page to clearly show polaris-reporting
  pkg/synopsysctl/cmd_update.go
Labels: approved, lgtm, size/XS

#1253 Get Command for Polaris-Reporting
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_get.go
  pkg/util/helm_helpers.go
Labels: approved, size/M

#1260 [master] Get Command for Polaris-Reporting
  pkg/synopsysctl/cmd_delete.go
  pkg/synopsysctl/cmd_get.go
  pkg/util/helm_helpers.go
Labels: size/M

#1257 Helm flag Mapping Function
  pkg/polaris-reporting/ctl_polarisreporting.go
  pkg/polaris-reporting/helpers.go
  pkg/polaris-reporting/helpers_test.go
Labels: approved, size/L

#1263 add 5.0.2, 5.2.1 and 5.2.2 support
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, size/S

#1264 add alert 5.2.2 supoort
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, size/XS

#1265 [master] add alert 5.2.2 supoort
  pkg/apps/alert/latest/alert_versions.go
Labels: approved, lgtm, size/XS

#1266 make storage class mandatory and don't make them to update
  pkg/polaris-reporting/ctl_polarisreporting.go
Labels: approved, lgtm, size/XS

#1267 [master] make storage class mandatory and don't make them to update
  pkg/polaris-reporting/ctl_polarisreporting.go
Labels: approved, lgtm, size/XS

#1269 update default chart repository and default reporting version
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/S

#1270 [master] update default chart repository and default reporting version
  pkg/synopsysctl/cmd_create.go
  pkg/synopsysctl/cmd_update.go
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/S

#1268 fix setting env value to /tmp/secrets for certificates
  pkg/apps/alert/latest/alertdeployment.go
Labels: approved, lgtm, size/XS

#1271 removed the reductant synopsys in chartmuseum url
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/XS

#1272 [release-2020.2.x] fix setting env value to /tmp/secrets for certificates
  pkg/apps/alert/latest/alertdeployment.go
Labels: approved, lgtm, size/XS

#1273 [master] removed the reductant synopsys in chartmuseum url
  pkg/synopsysctl/constants.go
Labels: approved, lgtm, size/XS
